// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserLicense = "user_licenses"

// UserLicense mapped from table <user_licenses>
type UserLicense struct {
	Type  LicenseType `gorm:"column:type;type:varchar(60);primaryKey" json:"type"`
	Owner string      `gorm:"column:owner;type:varchar(64);primaryKey;index:idx_user_licenses_owner,priority:1" json:"-"`
}

// TableName UserLicense's table name
func (*UserLicense) TableName() string {
	return TableNameUserLicense
}
