//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ArpanetDocumentsJobAccess struct {
	ID           uint64     `sql:"primary_key" json:"id"`
	CreatedAt    *time.Time `json:"created_at"`
	UpdatedAt    *time.Time `json:"updated_at"`
	DocumentID   uint64     `json:"document_id"`
	Name         string     `json:"name"`
	MinimumGrade int32      `json:"minimum_grade"`
	Access       string     `json:"access"`
}
