//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ArpanetRoles struct {
	ID          uint64 `sql:"primary_key"`
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
	Name        string
	GuardName   string
	Description *string
}
