//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type JobGrades struct {
	JobName    string `sql:"primary_key"`
	Grade      int32  `sql:"primary_key"`
	Name       string
	Label      string
	Salary     int32
	SkinMale   string
	SkinFemale string
}
