// Code generated by protoc-gen-customizer. DO NOT EDIT.
// source: services/rector/rector.proto

package rector

import "github.com/galexrt/fivenet/pkg/perms"

var PermsRemap = map[string]string{
	// Service: RectorService
	"RectorService/GetRole":            "RectorService/GetRoles",
	"RectorService/RemovePermFromRole": "RectorService/AddPermToRole",
}

func (s *Server) GetPermsRemap() map[string]string {
	return PermsRemap
}

const (
	RectorServicePermKey = "RectorService"
)

func init() {
	perms.AddPermsToList([]*perms.Perm{
		// Service: RectorService
		{
			Key:         RectorServicePermKey,
			Name:        "AddPermToRole",
			Description: "Add/ Delete permissions to FiveNet job roles",
		},
		{
			Key:         RectorServicePermKey,
			Name:        "CreateRole",
			Description: "Create rank-specific FiveNet job roles",
		},
		{
			Key:         RectorServicePermKey,
			Name:        "DeleteRole",
			Description: "Delete FiveNet job roles",
		},
		{
			Key:         RectorServicePermKey,
			Name:        "GetPermissions",
			PerJob:      true,
			Description: "Get list of available FiveNet job roles permissions",
		},
		{
			Key:         RectorServicePermKey,
			Name:        "GetRoles",
			Description: "Get/List FiveNet job roles",
		},
		{
			Key:         RectorServicePermKey,
			Name:        "ViewAuditLog",
			Description: "View audit log",
		},
	})
}
