import {
    AlarmLightIcon,
    AlertIcon,
    AlertOctagonIcon,
    CrosshairsGpsIcon,
    EmoticonDevilIcon,
    ExclamationThickIcon,
    HelpIcon,
    HospitalBoxIcon,
    MedicalBagIcon,
    MinusCircleIcon,
    OctagonIcon,
    PistolIcon,
    PoliceBadgeIcon,
    PoliceStationIcon,
    RhombusSplitIcon,
    SignCautionIcon,
    SwordCrossIcon,
    TooltipIcon,
    TooltipTextIcon,
} from 'mdi-vue3';

export const markerIcons = markRaw([
    HelpIcon,
    SignCautionIcon,
    AlertIcon,
    AlarmLightIcon,
    ExclamationThickIcon,
    AlertOctagonIcon,
    OctagonIcon,
    MinusCircleIcon,
    MedicalBagIcon,
    HospitalBoxIcon,
    PoliceBadgeIcon,
    PoliceStationIcon,
    TooltipIcon,
    TooltipTextIcon,
    PistolIcon,
    RhombusSplitIcon,
    SwordCrossIcon,
    CrosshairsGpsIcon,
    EmoticonDevilIcon,
]);
