{{- if .Values.iconify.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fivenet.fullname" . }}-iconify
  labels:
    {{- include "fivenet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.iconify.replicaCount }}
  revisionHistoryLimit: {{ .Values.iconify.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/component: iconify
      {{- include "fivenet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/fivenet-config: {{ include (print $.Template.BasePath "/secrets.yaml") $ | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: iconify
        {{- include "fivenet.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fivenet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: iconify
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.iconify.image.repository }}:{{ .Values.iconify.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.iconify.image.pullPolicy }}
          env:
            {{- toYaml .Values.iconify.additionalEnv | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          {{- with .Values.iconify.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.iconify.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.iconify.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.iconify.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
