{{- if .Values.discord.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fivenet.fullname" . }}-discord
  labels:
    app.kubernetes.io/component: discord
    {{- include "fivenet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: 7070
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/component: discord
    {{- include "fivenet.selectorLabels" . | nindent 4 }}
{{- end }}
