apiVersion: v1
kind: Service
metadata:
  name: {{ include "fivenet.fullname" . }}-envoy
  labels:
    app.kubernetes.io/component: envoy
    {{- include "fivenet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: 8181
      protocol: TCP
      targetPort: grpc
    - name: admin
      port: 9901
      protocol: TCP
      targetPort: admin
  selector:
    app.kubernetes.io/component: envoy
    {{- include "fivenet.selectorLabels" . | nindent 4 }}
