logLevel: "DEBUG"
# debug or release
mode: "debug"
sentry:
  environment: "dev"
  # Your Sentry or Glitchtip SDN
  clientDSN: ""
  serverDSN: "https://d3372a68f9b440618195a6893c3e95a3@glitchtip.edenmal.moe/2"
http:
  listen: ":8080"
  sessions:
    cookieSecret: "your_generated_cookie_secret"
    domain: "localhost"
grpc:
  listen: ":9090"
  # Must be https or on the same URL
  clientURL: "/grpc"
database:
  # refer to https://github.com/go-sql-driver/mysql#dsn-data-source-name for details
  dsn: "DB_USER:DB_PASS@tcp(DB_HOST:DB_PORT)/DB_NAME?collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
  # For the local test database using `docker-compose`
  #dsn: "fivenet:changeme@tcp(localhost:3306)/fivenet?collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
  dbName: fivenet
  maxOpenConns: 32
  maxIdleConns: 5
  connMaxIdleTime: 15m
  connMaxLifetime: 60m
jwt:
  secret: "your_generated_jwt_secret"
oauth2:
  providers:
    - name: "discord"
      label: "Discord"
      homepage: "https://discord.com"
      #defaultAvatar: ""
      type: "discord"
      redirectURL: "https://localhost:3000/api/oauth2/callback/discord"
      clientID: "your_discord_oauth2_client_id"
      clientSecret: "your_discord_oauth2_client_secret"
      scopes:
        - openid
        - identify
      endpoints:
        authURL: "https://discord.com/api/oauth2/authorize"
        tokenURL: "https://discord.com/api/oauth2/token"
game:
  superuserGroups:
    - projektleiter
    - teamleitung
  unemployedJob:
    name: "unemployed"
    grade: 1
  publicJobs:
    - ambulance
    - doj
    - fib
    - police
  permissionRoleJobs:
    - ambulance
    - doj
    - fib
    - police
  livemapJobs:
    - ambulance
    - doj
    - fib
    - police
