logLevel: "DEBUG"
# debug or release
mode: "debug"
tracing:
  enabled: false
  # Jaeger Tracing endpoint (should have the right API path in the URL `/api/traces`)
  url: ""
  environment: "dev"
  ratio: 0.1
http:
  listen: ":8080"
  adminListen: ":7070"
  sessions:
    cookieSecret: "your_generated_cookie_secret"
    domain: "localhost"
  links:
    imprint: "https://example.com/your_imprint/"
    privacyPolicy: "https://example.com/your_privacy_policy/"
grpc:
  listen: ":9090"
database:
  # refer to https://github.com/go-sql-driver/mysql#dsn-data-source-name for details
  dsn: "DB_USER:DB_PASS@tcp(DB_HOST:DB_PORT)/DB_NAME?collation=utf8mb4_unicode_ci&parseTime=True&loc=Europe%2FBerlin"
  # For the local test database using `docker-compose`
  #dsn: "fivenet:changeme@tcp(localhost:3306)/fivenet?collation=utf8mb4_unicode_ci&parseTime=True&loc=Europe%2FBerlin"
  maxOpenConns: 32
  maxIdleConns: 5
  connMaxIdleTime: 15m
  connMaxLifetime: 60m
nats:
  url: "nats://localhost:4222"
jwt:
  secret: "your_generated_jwt_secret"
oauth2:
  providers:
    - name: "discord"
      label: "Discord"
      homepage: "https://discord.com"
      #defaultAvatar: ""
      type: "discord"
      redirectURL: "https://localhost:3000/api/oauth2/callback/discord"
      clientID: "your_discord_oauth2_client_id"
      clientSecret: "your_discord_oauth2_client_secret"
      scopes:
        - openid
        - identify
      endpoints:
        authURL: "https://discord.com/api/oauth2/authorize"
        tokenURL: "https://discord.com/api/oauth2/token"
cache:
  refreshTime: 2m
audit:
  retentionDays: 90
game:
  auth:
    signupEnabled: true
    superuserGroups:
      - projektleiter
      - teamleitung
    defaultPermissions:
      - category: AuthService
        name: ChooseCharacter
      - category: CompletorService
        name: CompleteJobs
      - category: DocStoreService
        name: ListDocuments
      - category: DocStoreService
        name: GetDocument
      - category: DocStoreService
        name: PostComment
  unemployedJob:
    name: "unemployed"
    grade: 1
  publicJobs:
    - ambulance
    - doj
    - gov
    - police
  hiddenJobs: []
  livemap:
    refreshTime: 3s350ms
    dbRefreshTime: 1s
    jobs:
      - ambulance
      - doj
      - fib
      - police
    #postalsFile: ".output/public/data/postals.json"
  dispatchCenter:
    convertJobs: []
      #- police
discord:
  bot:
    enabled: true
    syncInterval: 15m
    inviteURL: "your_discord_bot_invite_url" # Recommended bot perms: `-42471713`
    token: "your_discord_bot_token"
    presence:
      gameStatus: "FiveNet"
      #listeningStatus: ""
      #streamingStatus: ""
      #streamingStatusUrl: ""
      #watchStatus: ""
    userInfoSync:
      enabled: false
      gradeRoleFormat: "[%grade%] %grade_label%"
      employeeRoleFormat: "%s Employees"
      unemployedRoleName: "Citizen"
      nicknameRegex: "^(?P<prefix>\\[\\S+][ ]*)?(?P<name>[^\\[]+)(?P<suffix>[ ]*\\[\\S+])?"
      ignoreJobs: []
      #  - army
      jobsAbsceneRoleName: "Absent"
    groupSync:
      enabled: false
      mapping:
        fraktionsverwaltung:
          roleName: "Fraktionsverwaltung"
          #permissions: 0
          #color: "#9B59B6"
          notSameJob: true
        teamleitung:
          roleName: "Teamleitung"
          #permissions: 0
          #color: "#9B59B6"
    commands:
      enabled: true
storage:
  type: "filesystem"
  filesystem:
    path: ".data/"
  s3:
    endpoint: ""
    region: "us-east-1"
    accessKeyID: ""
    secretAccessKey: ""
    useSSL: true
    bucketName: ""
    prefix: ""
imageProxy:
  enabled: true
  url: "/api/image_proxy/"
  cachePrefix: "images/"
  options:
    allowHosts: []
    denyHosts: []
