logLevel: "DEBUG"
# debug or release
mode: "debug"
sentry:
  environment: "dev"
  # Your Sentry or Glitchtip SDN
  clientDSN: ""
  serverDSN: "https://d3372a68f9b440618195a6893c3e95a3@glitchtip.edenmal.moe/2"
tracing:
  enabled: false
  # Jaeger Tracing endpoint (should have the right API path in the URL `/api/traces`)
  url: ""
  environment: "dev"
http:
  listen: ":8080"
  sessions:
    cookieSecret: "your_generated_cookie_secret"
    domain: "localhost"
  publicURL: "http://localhost:3000"
grpc:
  listen: ":9090"
database:
  # refer to https://github.com/go-sql-driver/mysql#dsn-data-source-name for details
  dsn: "DB_USER:DB_PASS@tcp(DB_HOST:DB_PORT)/DB_NAME?collation=utf8mb4_unicode_ci&parseTime=True&loc=Europe%2FBerlin"
  # For the local test database using `docker-compose`
  #dsn: "fivenet:changeme@tcp(localhost:3306)/fivenet?collation=utf8mb4_unicode_ci&parseTime=True&loc=Europe%2FBerlin"
  maxOpenConns: 32
  maxIdleConns: 5
  connMaxIdleTime: 15m
  connMaxLifetime: 60m
nats:
  url: "nats://localhost:4222"
  workerCount: 5
jwt:
  secret: "your_generated_jwt_secret"
oauth2:
  providers:
    - name: "discord"
      label: "Discord"
      homepage: "https://discord.com"
      #defaultAvatar: ""
      type: "discord"
      redirectURL: "https://localhost:3000/api/oauth2/callback/discord"
      clientID: "your_discord_oauth2_client_id"
      clientSecret: "your_discord_oauth2_client_secret"
      scopes:
        - openid
        - identify
      endpoints:
        authURL: "https://discord.com/api/oauth2/authorize"
        tokenURL: "https://discord.com/api/oauth2/token"
cache:
  refreshTime: 2m
game:
  signupEnabled: true
  auditRetentionDays: 90
  superuserGroups:
    - projektleiter
    - teamleitung
  unemployedJob:
    name: "unemployed"
    grade: 1
  publicJobs:
    - ambulance
    - doj
    - fib
    - police
  livemap:
    refreshTime: 3s350ms
    jobs:
      - ambulance
      - doj
      - fib
      - police
    #postalsFile: ".output/public/data/postals.json"
  dispatchCenter:
    convertJobs: []
      #- police
  defaultPermissions:
    - category: AuthService
      name: ChooseCharacter
    - category: CompletorService
      name: CompleteJobs
    - category: DocStoreService
      name: ListDocuments
    - category: DocStoreService
      name: GetDocument
    - category: DocStoreService
      name: PostComment
discord:
  bot:
    enabled: true
    syncInterval: 15m
    inviteURL: "your_discord_bot_invite_url"
    token: "your_discord_bot_token"
    userInfoSync:
      enabled: false
      roleFormat: "[%02d] %s"
      nicknameRegex: "^(?P<prefix>\\[\\S+][ ]*)?(?P<name>[^\\[]+)(?P<suffix>[ ]*\\[\\S+])?"
    groupSync:
      enabled: false
      mapping:
        fraktionsverwaltung:
          roleName: "Fraktionsverwaltung"
          #permissions: 0
        teamleitung:
          roleName: "Teamleitung"
          #permissions: 0
    commands:
      enabled: true
