#
# Be sure to checkout the Config file reference: https://fivenet.app/getting-started/configuration/config-reference
#
logLevel: "DEBUG"
# debug or release
mode: "release"
logLevels:
  nats.store: "INFO"
otlp:
  enabled: false
  # Can be "stdout", "grpc", "http"
  type: "stdout"
  # OTLP endpoint URL (must include `http(s)://`)
  url: "http://localhost:4317"
  insecure: false
  timeout: 10s
  environment: "dev"
  ratio: 0.1
  attributes: []
  # - service.name=fivenet-server
  headers: {}
    # Example to authenticate with an API key
    #authorization: "API_KEY_HERE"
  # Can be "none" or "gzip"
  compression: "none"
  frontend:
    url: ""
    headers: {}
      # Example to authenticate with an API key
      #authorization: "API_KEY_HERE"
http:
  listen: ":8080"
  adminListen: ":7070"
  publicURL: "https://fivenet.example.com"
  origins:
    - "https://fivenet.example.com"
    #- "http://localhost:3000" # Only for development
  trustedProxies: []
    #- "127.0.0.1" # Only for development
  sessions:
    cookieSecret: "your_generated_cookie_secret"
    domain: "fivenet.example.com"
database:
  # Refer to https://github.com/go-sql-driver/mysql#dsn-data-source-name for details
  # Please note that the `parseTime` parameter is allows set to true
  dsn: "DB_USER:DB_PASS@tcp(DB_HOST:DB_PORT)/DB_NAME?collation=utf8mb4_unicode_ci&loc=Europe%2FBerlin"
  # For the local test database using `docker-compose`
  #dsn: "fivenet:changeme@tcp(localhost:3306)/fivenet?collation=utf8mb4_unicode_ci&loc=Europe%2FBerlin"
  maxOpenConns: 32
  maxIdleConns: 5
  connMaxIdleTime: 15m
  connMaxLifetime: 60m
  # Must be enabled if using a gameserver database (with ESX tables) and not wanting to use the dbsync
  esxCompat: true
  custom:
    # To disable a column, set it to `"-"`
    columns:
      user:
        visum: "visum"
        playtime: "playtime"
      vehicle:
        model: "model"
    conditions:
      user:
        filterEmptyName: false
nats:
  # This NATS url is for using the NATS server from the `docker-compose.yaml`
  url: "nats://fivenet:fivenet_topsecret@nats:4222"
  replicas: 1
jwt:
  secret: "your_generated_jwt_secret"
storage:
  type: "filesystem"
  filesystem:
    path: ".data/"
    prefix: ""
  s3:
    endpoint: ""
    region: "us-east-1"
    accessKeyID: ""
    secretAccessKey: ""
    useSSL: true
    bucketName: ""
    prefix: ""
    retries: 3
    checkOnStartup: false
imageProxy:
  enabled: true
  url: "/api/image_proxy/"
  cachePrefix: "images/"
  options:
    allowHosts: []
    denyHosts: []
audit:
  retentionDays: 90
oauth2:
  providers:
    - name: "discord"
      label: "Discord"
      homepage: "https://discord.com"
      icon: "i-simple-icons-discord" # or an image URL
      #defaultAvatar: ""
      type: "discord"
      redirectURL: "https://localhost:3000/api/oauth2/callback/discord"
      clientID: "your_discord_oauth2_client_id"
      clientSecret: "your_discord_oauth2_client_secret"
      scopes:
        - openid
        - identify
      endpoints:
        authURL: "https://discord.com/api/oauth2/authorize"
        tokenURL: "https://discord.com/api/oauth2/token"
postalsFile: ".output/public/data/postals.json"
auth:
  superuserGroups:
    - projektleiter
    - teamleitung
  superuserUsers: []
dispatchCenter:
  type: "gksphone"
  convertJobs: []
    #- police
discord:
  enabled: true
  token: "your_discord_bot_token"
  userInfoSync:
    enabled: false
    gradeRoleFormat: "[%grade%] %grade_label%"
    employeeRoleFormat: "%s Employees"
    unemployedRoleName: "Citizen"
    jobsAbsceneRoleName: "Absent"
  groupSync:
    enabled: false
    mapping:
      fraktionsverwaltung:
        roleName: "Fraktionsverwaltung"
        #permissions: 0
        #color: "#9B59B6"
        notSameJob: true
      teamleitung:
        roleName: "Teamleitung"
        #permissions: 0
        #color: "#9B59B6"
  commands:
    enabled: true
game:
  # First grade "number/id", some servers start at 0, but I have seen some start at 1
  startJobGrade: 0
  # If enabled it will automatically delete roles which no jobs/grades are found for
  cleanupRolesForMissingJobs: false
sync:
  enabled: false
  apiTokens: []
    #- LONG_RANDOM_API_TOKEN_FOR_DBSYNC
