version: '3.5'

services:
  mysql:
    container_name: mysql
    image: mariadb:10.11.2-jammy
    environment:
      MYSQL_USER: ${MYSQL_USER:-arpanet}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-arpanet}
    volumes:
       - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    network_mode: host
    restart: unless-stopped

volumes:
  mysql:
