version: '3.5'

services:
  envoy:
    container_name: envoy
    image: envoyproxy/envoy-dev:f2e49c86b2edca1c65c7a375a7629f46d3c78e4e
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    network_mode: host
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: mariadb:10.11.2-jammy
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-secret-pw-for-root-user}
      MYSQL_USER: ${MYSQL_USER:-arpanet}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-arpanet}
    volumes:
       - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    network_mode: host
    restart: unless-stopped

volumes:
  mysql:
