version: '3.5'

services:
  # Used for testing only
  mysql:
    container_name: mysql
    image: docker.io/library/mysql:9.1.0
    command:
      - "mysqld"
      - "--innodb-ft-min-token-size=2"
      - "--innodb-ft-max-token-size=40"
      - "--default-time-zone=Europe/Berlin"
      - '--sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret-pw-for-root-user}
      MYSQL_USER: ${MYSQL_USER:-fivenet}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fivenet}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    network_mode: host
    restart: unless-stopped

  # Message Queue
  nats:
    container_name: nats
    image: docker.io/library/nats:2.10.7-alpine3.18
    command:
      - --jetstream
      # If you change the user/password, you must update the `.nats.url` in FiveNet's `config.yaml`
      - --user=fivenet
      - --pass=fivenet_topsecret
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    network_mode: host
    restart: unless-stopped

  # FiveNet Server
  #fivenet_server:
  #  container_name: fivenet-server
  #  image: ghcr.io/fivenet-app/fivenet:main
  #  command:
  #    - server
  #  ports:
  #    - "7070:7070"
  #    - "8080:8080"
  #  network_mode: host
  #  restart: unless-stopped
  #  volumes:
  #    - ./config.yaml:/config/config.yaml
  # FiveNet Worker
  #fivenet_worker:
  #  container_name: fivenet-worker
  #  image: ghcr.io/fivenet-app/fivenet:main
  #  command:
  #    - worker
  #  ports:
  #    - "7070:7070"
  #  restart: unless-stopped
  #  volumes:
  #    - ./config.yaml:/config/config.yaml
  # FiveNet Discord
  #fivenet_discord:
  #  container_name: fivenet-discord
  #  image: ghcr.io/fivenet-app/fivenet:main
  #  command:
  #    - discord
  #  ports:
  #    - "7070:7070"
  #  restart: unless-stopped
  #  volumes:
  #    - ./config.yaml:/config/config.yaml

  # Iconify - Requires an ingress like Traefik that makes iconify available under `/api/icons`
  #iconify:
  #  container_name: iconify
  #  image: docker.io/iconify/api:latest
  #  environment:
  #    ICONIFY_SOURCE: "full"
  #    REDIRECT_INDEX: "/about"
  #    ALLOW_UPDATE: "false"
  #    ENABLE_ICON_LISTS: "false"
  #    ENABLE_SEARCH_ENGINE: "false"
  #  ports:
  #    - "3000:3000"

volumes:
  mysql:
