version: '3.5'

services:
  envoy:
    container_name: envoy
    image: docker.io/envoyproxy/envoy:v1.26.2
    environment:
      - ENVOY_UID=0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ${HOME}/.vite-plugin-mkcert:/certs:ro
    user: 0:0
    ports:
      - "8181:8181"
    network_mode: host
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: docker.io/library/mariadb:10.11.4-jammy
    command:
      - "mariadbd"
      - "--innodb-ft-min-token-size=2"
      - "--innodb-ft-max-token-size=40"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret-pw-for-root-user}
      MYSQL_USER: ${MYSQL_USER:-fivenet}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-fivenet}
    volumes:
       - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    network_mode: host
    restart: unless-stopped

  nats:
    container_name: nats
    image: docker.io/library/nats:2.9.19-alpine3.18
    command:
      - --jetstream
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    network_mode: host
    restart: unless-stopped

volumes:
  mysql:
