//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetJobsQualificationsReqsAccess = newFivenetJobsQualificationsReqsAccessTable("", "fivenet_jobs_qualifications_reqs_access", "")

type fivenetJobsQualificationsReqsAccessTable struct {
	mysql.Table

	// Columns
	ID                    mysql.ColumnInteger
	CreatedAt             mysql.ColumnTimestamp
	QualificationID       mysql.ColumnInteger
	TargetQualificationID mysql.ColumnInteger
	Access                mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FivenetJobsQualificationsReqsAccessTable struct {
	fivenetJobsQualificationsReqsAccessTable

	NEW fivenetJobsQualificationsReqsAccessTable
}

// AS creates new FivenetJobsQualificationsReqsAccessTable with assigned alias
func (a FivenetJobsQualificationsReqsAccessTable) AS(alias string) *FivenetJobsQualificationsReqsAccessTable {
	return newFivenetJobsQualificationsReqsAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetJobsQualificationsReqsAccessTable with assigned schema name
func (a FivenetJobsQualificationsReqsAccessTable) FromSchema(schemaName string) *FivenetJobsQualificationsReqsAccessTable {
	return newFivenetJobsQualificationsReqsAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetJobsQualificationsReqsAccessTable with assigned table prefix
func (a FivenetJobsQualificationsReqsAccessTable) WithPrefix(prefix string) *FivenetJobsQualificationsReqsAccessTable {
	return newFivenetJobsQualificationsReqsAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetJobsQualificationsReqsAccessTable with assigned table suffix
func (a FivenetJobsQualificationsReqsAccessTable) WithSuffix(suffix string) *FivenetJobsQualificationsReqsAccessTable {
	return newFivenetJobsQualificationsReqsAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetJobsQualificationsReqsAccessTable(schemaName, tableName, alias string) *FivenetJobsQualificationsReqsAccessTable {
	return &FivenetJobsQualificationsReqsAccessTable{
		fivenetJobsQualificationsReqsAccessTable: newFivenetJobsQualificationsReqsAccessTableImpl(schemaName, tableName, alias),
		NEW:                                      newFivenetJobsQualificationsReqsAccessTableImpl("", "new", ""),
	}
}

func newFivenetJobsQualificationsReqsAccessTableImpl(schemaName, tableName, alias string) fivenetJobsQualificationsReqsAccessTable {
	var (
		IDColumn                    = mysql.IntegerColumn("id")
		CreatedAtColumn             = mysql.TimestampColumn("created_at")
		QualificationIDColumn       = mysql.IntegerColumn("qualification_id")
		TargetQualificationIDColumn = mysql.IntegerColumn("target_qualification_id")
		AccessColumn                = mysql.IntegerColumn("access")
		allColumns                  = mysql.ColumnList{IDColumn, CreatedAtColumn, QualificationIDColumn, TargetQualificationIDColumn, AccessColumn}
		mutableColumns              = mysql.ColumnList{CreatedAtColumn, QualificationIDColumn, TargetQualificationIDColumn, AccessColumn}
	)

	return fivenetJobsQualificationsReqsAccessTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                    IDColumn,
		CreatedAt:             CreatedAtColumn,
		QualificationID:       QualificationIDColumn,
		TargetQualificationID: TargetQualificationIDColumn,
		Access:                AccessColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
