//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetMailerEmailsQualificationsAccess = newFivenetMailerEmailsQualificationsAccessTable("", "fivenet_mailer_emails_qualifications_access", "")

type fivenetMailerEmailsQualificationsAccessTable struct {
	mysql.Table

	// Columns
	ID              mysql.ColumnInteger
	CreatedAt       mysql.ColumnTimestamp
	EmailID         mysql.ColumnInteger
	QualificationID mysql.ColumnInteger
	Access          mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FivenetMailerEmailsQualificationsAccessTable struct {
	fivenetMailerEmailsQualificationsAccessTable

	NEW fivenetMailerEmailsQualificationsAccessTable
}

// AS creates new FivenetMailerEmailsQualificationsAccessTable with assigned alias
func (a FivenetMailerEmailsQualificationsAccessTable) AS(alias string) *FivenetMailerEmailsQualificationsAccessTable {
	return newFivenetMailerEmailsQualificationsAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetMailerEmailsQualificationsAccessTable with assigned schema name
func (a FivenetMailerEmailsQualificationsAccessTable) FromSchema(schemaName string) *FivenetMailerEmailsQualificationsAccessTable {
	return newFivenetMailerEmailsQualificationsAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetMailerEmailsQualificationsAccessTable with assigned table prefix
func (a FivenetMailerEmailsQualificationsAccessTable) WithPrefix(prefix string) *FivenetMailerEmailsQualificationsAccessTable {
	return newFivenetMailerEmailsQualificationsAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetMailerEmailsQualificationsAccessTable with assigned table suffix
func (a FivenetMailerEmailsQualificationsAccessTable) WithSuffix(suffix string) *FivenetMailerEmailsQualificationsAccessTable {
	return newFivenetMailerEmailsQualificationsAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetMailerEmailsQualificationsAccessTable(schemaName, tableName, alias string) *FivenetMailerEmailsQualificationsAccessTable {
	return &FivenetMailerEmailsQualificationsAccessTable{
		fivenetMailerEmailsQualificationsAccessTable: newFivenetMailerEmailsQualificationsAccessTableImpl(schemaName, tableName, alias),
		NEW: newFivenetMailerEmailsQualificationsAccessTableImpl("", "new", ""),
	}
}

func newFivenetMailerEmailsQualificationsAccessTableImpl(schemaName, tableName, alias string) fivenetMailerEmailsQualificationsAccessTable {
	var (
		IDColumn              = mysql.IntegerColumn("id")
		CreatedAtColumn       = mysql.TimestampColumn("created_at")
		EmailIDColumn         = mysql.IntegerColumn("email_id")
		QualificationIDColumn = mysql.IntegerColumn("qualification_id")
		AccessColumn          = mysql.IntegerColumn("access")
		allColumns            = mysql.ColumnList{IDColumn, CreatedAtColumn, EmailIDColumn, QualificationIDColumn, AccessColumn}
		mutableColumns        = mysql.ColumnList{CreatedAtColumn, EmailIDColumn, QualificationIDColumn, AccessColumn}
	)

	return fivenetMailerEmailsQualificationsAccessTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CreatedAt:       CreatedAtColumn,
		EmailID:         EmailIDColumn,
		QualificationID: QualificationIDColumn,
		Access:          AccessColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
