//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetJobAttrs = newFivenetJobAttrsTable("", "fivenet_job_attrs", "")

type fivenetJobAttrsTable struct {
	mysql.Table

	// Columns
	Job       mysql.ColumnString
	AttrID    mysql.ColumnInteger
	MaxValues mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetJobAttrsTable struct {
	fivenetJobAttrsTable

	NEW fivenetJobAttrsTable
}

// AS creates new FivenetJobAttrsTable with assigned alias
func (a FivenetJobAttrsTable) AS(alias string) *FivenetJobAttrsTable {
	return newFivenetJobAttrsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetJobAttrsTable with assigned schema name
func (a FivenetJobAttrsTable) FromSchema(schemaName string) *FivenetJobAttrsTable {
	return newFivenetJobAttrsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetJobAttrsTable with assigned table prefix
func (a FivenetJobAttrsTable) WithPrefix(prefix string) *FivenetJobAttrsTable {
	return newFivenetJobAttrsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetJobAttrsTable with assigned table suffix
func (a FivenetJobAttrsTable) WithSuffix(suffix string) *FivenetJobAttrsTable {
	return newFivenetJobAttrsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetJobAttrsTable(schemaName, tableName, alias string) *FivenetJobAttrsTable {
	return &FivenetJobAttrsTable{
		fivenetJobAttrsTable: newFivenetJobAttrsTableImpl(schemaName, tableName, alias),
		NEW:                  newFivenetJobAttrsTableImpl("", "new", ""),
	}
}

func newFivenetJobAttrsTableImpl(schemaName, tableName, alias string) fivenetJobAttrsTable {
	var (
		JobColumn       = mysql.StringColumn("job")
		AttrIDColumn    = mysql.IntegerColumn("attr_id")
		MaxValuesColumn = mysql.StringColumn("max_values")
		allColumns      = mysql.ColumnList{JobColumn, AttrIDColumn, MaxValuesColumn}
		mutableColumns  = mysql.ColumnList{MaxValuesColumn}
		defaultColumns  = mysql.ColumnList{}
	)

	return fivenetJobAttrsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Job:       JobColumn,
		AttrID:    AttrIDColumn,
		MaxValues: MaxValuesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
