//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetJobTimeclock = newFivenetJobTimeclockTable("", "fivenet_job_timeclock", "")

type fivenetJobTimeclockTable struct {
	mysql.Table

	// Columns
	Job       mysql.ColumnString
	UserID    mysql.ColumnInteger
	Date      mysql.ColumnDate
	StartTime mysql.ColumnTimestamp
	EndTime   mysql.ColumnTimestamp
	SpentTime mysql.ColumnFloat

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetJobTimeclockTable struct {
	fivenetJobTimeclockTable

	NEW fivenetJobTimeclockTable
}

// AS creates new FivenetJobTimeclockTable with assigned alias
func (a FivenetJobTimeclockTable) AS(alias string) *FivenetJobTimeclockTable {
	return newFivenetJobTimeclockTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetJobTimeclockTable with assigned schema name
func (a FivenetJobTimeclockTable) FromSchema(schemaName string) *FivenetJobTimeclockTable {
	return newFivenetJobTimeclockTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetJobTimeclockTable with assigned table prefix
func (a FivenetJobTimeclockTable) WithPrefix(prefix string) *FivenetJobTimeclockTable {
	return newFivenetJobTimeclockTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetJobTimeclockTable with assigned table suffix
func (a FivenetJobTimeclockTable) WithSuffix(suffix string) *FivenetJobTimeclockTable {
	return newFivenetJobTimeclockTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetJobTimeclockTable(schemaName, tableName, alias string) *FivenetJobTimeclockTable {
	return &FivenetJobTimeclockTable{
		fivenetJobTimeclockTable: newFivenetJobTimeclockTableImpl(schemaName, tableName, alias),
		NEW:                      newFivenetJobTimeclockTableImpl("", "new", ""),
	}
}

func newFivenetJobTimeclockTableImpl(schemaName, tableName, alias string) fivenetJobTimeclockTable {
	var (
		JobColumn       = mysql.StringColumn("job")
		UserIDColumn    = mysql.IntegerColumn("user_id")
		DateColumn      = mysql.DateColumn("date")
		StartTimeColumn = mysql.TimestampColumn("start_time")
		EndTimeColumn   = mysql.TimestampColumn("end_time")
		SpentTimeColumn = mysql.FloatColumn("spent_time")
		allColumns      = mysql.ColumnList{JobColumn, UserIDColumn, DateColumn, StartTimeColumn, EndTimeColumn, SpentTimeColumn}
		mutableColumns  = mysql.ColumnList{JobColumn, UserIDColumn, DateColumn, StartTimeColumn, EndTimeColumn, SpentTimeColumn}
		defaultColumns  = mysql.ColumnList{DateColumn, StartTimeColumn, SpentTimeColumn}
	)

	return fivenetJobTimeclockTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Job:       JobColumn,
		UserID:    UserIDColumn,
		Date:      DateColumn,
		StartTime: StartTimeColumn,
		EndTime:   EndTimeColumn,
		SpentTime: SpentTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
