//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetCentrumQualificationsAccess = newFivenetCentrumQualificationsAccessTable("", "fivenet_centrum_qualifications_access", "")

type fivenetCentrumQualificationsAccessTable struct {
	mysql.Table

	// Columns
	ID              mysql.ColumnInteger
	CreatedAt       mysql.ColumnTimestamp
	UnitID          mysql.ColumnInteger
	QualificationID mysql.ColumnInteger
	Access          mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetCentrumQualificationsAccessTable struct {
	fivenetCentrumQualificationsAccessTable

	NEW fivenetCentrumQualificationsAccessTable
}

// AS creates new FivenetCentrumQualificationsAccessTable with assigned alias
func (a FivenetCentrumQualificationsAccessTable) AS(alias string) *FivenetCentrumQualificationsAccessTable {
	return newFivenetCentrumQualificationsAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetCentrumQualificationsAccessTable with assigned schema name
func (a FivenetCentrumQualificationsAccessTable) FromSchema(schemaName string) *FivenetCentrumQualificationsAccessTable {
	return newFivenetCentrumQualificationsAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetCentrumQualificationsAccessTable with assigned table prefix
func (a FivenetCentrumQualificationsAccessTable) WithPrefix(prefix string) *FivenetCentrumQualificationsAccessTable {
	return newFivenetCentrumQualificationsAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetCentrumQualificationsAccessTable with assigned table suffix
func (a FivenetCentrumQualificationsAccessTable) WithSuffix(suffix string) *FivenetCentrumQualificationsAccessTable {
	return newFivenetCentrumQualificationsAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetCentrumQualificationsAccessTable(schemaName, tableName, alias string) *FivenetCentrumQualificationsAccessTable {
	return &FivenetCentrumQualificationsAccessTable{
		fivenetCentrumQualificationsAccessTable: newFivenetCentrumQualificationsAccessTableImpl(schemaName, tableName, alias),
		NEW:                                     newFivenetCentrumQualificationsAccessTableImpl("", "new", ""),
	}
}

func newFivenetCentrumQualificationsAccessTableImpl(schemaName, tableName, alias string) fivenetCentrumQualificationsAccessTable {
	var (
		IDColumn              = mysql.IntegerColumn("id")
		CreatedAtColumn       = mysql.TimestampColumn("created_at")
		UnitIDColumn          = mysql.IntegerColumn("unit_id")
		QualificationIDColumn = mysql.IntegerColumn("qualification_id")
		AccessColumn          = mysql.IntegerColumn("access")
		allColumns            = mysql.ColumnList{IDColumn, CreatedAtColumn, UnitIDColumn, QualificationIDColumn, AccessColumn}
		mutableColumns        = mysql.ColumnList{CreatedAtColumn, UnitIDColumn, QualificationIDColumn, AccessColumn}
		defaultColumns        = mysql.ColumnList{CreatedAtColumn}
	)

	return fivenetCentrumQualificationsAccessTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		CreatedAt:       CreatedAtColumn,
		UnitID:          UnitIDColumn,
		QualificationID: QualificationIDColumn,
		Access:          AccessColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
