//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetWikiPagesVisibilityCreator = newFivenetWikiPagesVisibilityCreatorTable("", "fivenet_wiki_pages_visibility_creator", "")

type fivenetWikiPagesVisibilityCreatorTable struct {
	mysql.Table

	// Columns
	TargetID   mysql.ColumnInteger
	CreatorID  mysql.ColumnInteger
	CreatorJob mysql.ColumnString
	CreatedAt  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetWikiPagesVisibilityCreatorTable struct {
	fivenetWikiPagesVisibilityCreatorTable

	NEW fivenetWikiPagesVisibilityCreatorTable
}

// AS creates new FivenetWikiPagesVisibilityCreatorTable with assigned alias
func (a FivenetWikiPagesVisibilityCreatorTable) AS(alias string) *FivenetWikiPagesVisibilityCreatorTable {
	return newFivenetWikiPagesVisibilityCreatorTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetWikiPagesVisibilityCreatorTable with assigned schema name
func (a FivenetWikiPagesVisibilityCreatorTable) FromSchema(schemaName string) *FivenetWikiPagesVisibilityCreatorTable {
	return newFivenetWikiPagesVisibilityCreatorTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetWikiPagesVisibilityCreatorTable with assigned table prefix
func (a FivenetWikiPagesVisibilityCreatorTable) WithPrefix(prefix string) *FivenetWikiPagesVisibilityCreatorTable {
	return newFivenetWikiPagesVisibilityCreatorTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetWikiPagesVisibilityCreatorTable with assigned table suffix
func (a FivenetWikiPagesVisibilityCreatorTable) WithSuffix(suffix string) *FivenetWikiPagesVisibilityCreatorTable {
	return newFivenetWikiPagesVisibilityCreatorTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetWikiPagesVisibilityCreatorTable(schemaName, tableName, alias string) *FivenetWikiPagesVisibilityCreatorTable {
	return &FivenetWikiPagesVisibilityCreatorTable{
		fivenetWikiPagesVisibilityCreatorTable: newFivenetWikiPagesVisibilityCreatorTableImpl(schemaName, tableName, alias),
		NEW:                                    newFivenetWikiPagesVisibilityCreatorTableImpl("", "new", ""),
	}
}

func newFivenetWikiPagesVisibilityCreatorTableImpl(schemaName, tableName, alias string) fivenetWikiPagesVisibilityCreatorTable {
	var (
		TargetIDColumn   = mysql.IntegerColumn("target_id")
		CreatorIDColumn  = mysql.IntegerColumn("creator_id")
		CreatorJobColumn = mysql.StringColumn("creator_job")
		CreatedAtColumn  = mysql.TimestampColumn("created_at")
		allColumns       = mysql.ColumnList{TargetIDColumn, CreatorIDColumn, CreatorJobColumn, CreatedAtColumn}
		mutableColumns   = mysql.ColumnList{CreatorIDColumn, CreatorJobColumn, CreatedAtColumn}
		defaultColumns   = mysql.ColumnList{CreatedAtColumn}
	)

	return fivenetWikiPagesVisibilityCreatorTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TargetID:   TargetIDColumn,
		CreatorID:  CreatorIDColumn,
		CreatorJob: CreatorJobColumn,
		CreatedAt:  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
