//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetDocumentsSignaturePolicies = newFivenetDocumentsSignaturePoliciesTable("", "fivenet_documents_signature_policies", "")

type fivenetDocumentsSignaturePoliciesTable struct {
	mysql.Table

	// Columns
	DocumentID       mysql.ColumnInteger
	SnapshotDate     mysql.ColumnTimestamp
	BindingMode      mysql.ColumnInteger
	RuleKind         mysql.ColumnInteger
	RequiredCount    mysql.ColumnInteger
	AllowedTypesMask mysql.ColumnString
	DueAt            mysql.ColumnTimestamp
	AssignedCount    mysql.ColumnInteger
	ApprovedCount    mysql.ColumnInteger
	DeclinedCount    mysql.ColumnInteger
	PendingCount     mysql.ColumnInteger
	AnyDeclined      mysql.ColumnBool
	StartedAt        mysql.ColumnTimestamp
	CompletedAt      mysql.ColumnTimestamp
	CreatedAt        mysql.ColumnTimestamp
	UpdatedAt        mysql.ColumnTimestamp
	DeletedAt        mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetDocumentsSignaturePoliciesTable struct {
	fivenetDocumentsSignaturePoliciesTable

	NEW fivenetDocumentsSignaturePoliciesTable
}

// AS creates new FivenetDocumentsSignaturePoliciesTable with assigned alias
func (a FivenetDocumentsSignaturePoliciesTable) AS(alias string) *FivenetDocumentsSignaturePoliciesTable {
	return newFivenetDocumentsSignaturePoliciesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetDocumentsSignaturePoliciesTable with assigned schema name
func (a FivenetDocumentsSignaturePoliciesTable) FromSchema(schemaName string) *FivenetDocumentsSignaturePoliciesTable {
	return newFivenetDocumentsSignaturePoliciesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetDocumentsSignaturePoliciesTable with assigned table prefix
func (a FivenetDocumentsSignaturePoliciesTable) WithPrefix(prefix string) *FivenetDocumentsSignaturePoliciesTable {
	return newFivenetDocumentsSignaturePoliciesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetDocumentsSignaturePoliciesTable with assigned table suffix
func (a FivenetDocumentsSignaturePoliciesTable) WithSuffix(suffix string) *FivenetDocumentsSignaturePoliciesTable {
	return newFivenetDocumentsSignaturePoliciesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetDocumentsSignaturePoliciesTable(schemaName, tableName, alias string) *FivenetDocumentsSignaturePoliciesTable {
	return &FivenetDocumentsSignaturePoliciesTable{
		fivenetDocumentsSignaturePoliciesTable: newFivenetDocumentsSignaturePoliciesTableImpl(schemaName, tableName, alias),
		NEW:                                    newFivenetDocumentsSignaturePoliciesTableImpl("", "new", ""),
	}
}

func newFivenetDocumentsSignaturePoliciesTableImpl(schemaName, tableName, alias string) fivenetDocumentsSignaturePoliciesTable {
	var (
		DocumentIDColumn       = mysql.IntegerColumn("document_id")
		SnapshotDateColumn     = mysql.TimestampColumn("snapshot_date")
		BindingModeColumn      = mysql.IntegerColumn("binding_mode")
		RuleKindColumn         = mysql.IntegerColumn("rule_kind")
		RequiredCountColumn    = mysql.IntegerColumn("required_count")
		AllowedTypesMaskColumn = mysql.StringColumn("allowed_types_mask")
		DueAtColumn            = mysql.TimestampColumn("due_at")
		AssignedCountColumn    = mysql.IntegerColumn("assigned_count")
		ApprovedCountColumn    = mysql.IntegerColumn("approved_count")
		DeclinedCountColumn    = mysql.IntegerColumn("declined_count")
		PendingCountColumn     = mysql.IntegerColumn("pending_count")
		AnyDeclinedColumn      = mysql.BoolColumn("any_declined")
		StartedAtColumn        = mysql.TimestampColumn("started_at")
		CompletedAtColumn      = mysql.TimestampColumn("completed_at")
		CreatedAtColumn        = mysql.TimestampColumn("created_at")
		UpdatedAtColumn        = mysql.TimestampColumn("updated_at")
		DeletedAtColumn        = mysql.TimestampColumn("deleted_at")
		allColumns             = mysql.ColumnList{DocumentIDColumn, SnapshotDateColumn, BindingModeColumn, RuleKindColumn, RequiredCountColumn, AllowedTypesMaskColumn, DueAtColumn, AssignedCountColumn, ApprovedCountColumn, DeclinedCountColumn, PendingCountColumn, AnyDeclinedColumn, StartedAtColumn, CompletedAtColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns         = mysql.ColumnList{SnapshotDateColumn, BindingModeColumn, RuleKindColumn, RequiredCountColumn, AllowedTypesMaskColumn, DueAtColumn, AssignedCountColumn, ApprovedCountColumn, DeclinedCountColumn, PendingCountColumn, AnyDeclinedColumn, StartedAtColumn, CompletedAtColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		defaultColumns         = mysql.ColumnList{RuleKindColumn, RequiredCountColumn, AllowedTypesMaskColumn, AssignedCountColumn, ApprovedCountColumn, DeclinedCountColumn, PendingCountColumn, AnyDeclinedColumn, CreatedAtColumn}
	)

	return fivenetDocumentsSignaturePoliciesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		DocumentID:       DocumentIDColumn,
		SnapshotDate:     SnapshotDateColumn,
		BindingMode:      BindingModeColumn,
		RuleKind:         RuleKindColumn,
		RequiredCount:    RequiredCountColumn,
		AllowedTypesMask: AllowedTypesMaskColumn,
		DueAt:            DueAtColumn,
		AssignedCount:    AssignedCountColumn,
		ApprovedCount:    ApprovedCountColumn,
		DeclinedCount:    DeclinedCountColumn,
		PendingCount:     PendingCountColumn,
		AnyDeclined:      AnyDeclinedColumn,
		StartedAt:        StartedAtColumn,
		CompletedAt:      CompletedAtColumn,
		CreatedAt:        CreatedAtColumn,
		UpdatedAt:        UpdatedAtColumn,
		DeletedAt:        DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
