//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetDocumentsStatsMetric = newFivenetDocumentsStatsMetricTable("", "fivenet_documents_stats_metric", "")

type fivenetDocumentsStatsMetricTable struct {
	mysql.Table

	// Columns
	ID         mysql.ColumnInteger
	DocumentID mysql.ColumnInteger
	Job        mysql.ColumnString
	SourceKey  mysql.ColumnString
	MetricKey  mysql.ColumnString
	Dimension1 mysql.ColumnString
	Dimension2 mysql.ColumnString
	Dimension3 mysql.ColumnString
	Value      mysql.ColumnInteger
	OccurredAt mysql.ColumnTimestamp
	CreatedAt  mysql.ColumnTimestamp
	UpdatedAt  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetDocumentsStatsMetricTable struct {
	fivenetDocumentsStatsMetricTable

	NEW fivenetDocumentsStatsMetricTable
}

// AS creates new FivenetDocumentsStatsMetricTable with assigned alias
func (a FivenetDocumentsStatsMetricTable) AS(alias string) *FivenetDocumentsStatsMetricTable {
	return newFivenetDocumentsStatsMetricTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetDocumentsStatsMetricTable with assigned schema name
func (a FivenetDocumentsStatsMetricTable) FromSchema(schemaName string) *FivenetDocumentsStatsMetricTable {
	return newFivenetDocumentsStatsMetricTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetDocumentsStatsMetricTable with assigned table prefix
func (a FivenetDocumentsStatsMetricTable) WithPrefix(prefix string) *FivenetDocumentsStatsMetricTable {
	return newFivenetDocumentsStatsMetricTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetDocumentsStatsMetricTable with assigned table suffix
func (a FivenetDocumentsStatsMetricTable) WithSuffix(suffix string) *FivenetDocumentsStatsMetricTable {
	return newFivenetDocumentsStatsMetricTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetDocumentsStatsMetricTable(schemaName, tableName, alias string) *FivenetDocumentsStatsMetricTable {
	return &FivenetDocumentsStatsMetricTable{
		fivenetDocumentsStatsMetricTable: newFivenetDocumentsStatsMetricTableImpl(schemaName, tableName, alias),
		NEW:                              newFivenetDocumentsStatsMetricTableImpl("", "new", ""),
	}
}

func newFivenetDocumentsStatsMetricTableImpl(schemaName, tableName, alias string) fivenetDocumentsStatsMetricTable {
	var (
		IDColumn         = mysql.IntegerColumn("id")
		DocumentIDColumn = mysql.IntegerColumn("document_id")
		JobColumn        = mysql.StringColumn("job")
		SourceKeyColumn  = mysql.StringColumn("source_key")
		MetricKeyColumn  = mysql.StringColumn("metric_key")
		Dimension1Column = mysql.StringColumn("dimension1")
		Dimension2Column = mysql.StringColumn("dimension2")
		Dimension3Column = mysql.StringColumn("dimension3")
		ValueColumn      = mysql.IntegerColumn("value")
		OccurredAtColumn = mysql.TimestampColumn("occurred_at")
		CreatedAtColumn  = mysql.TimestampColumn("created_at")
		UpdatedAtColumn  = mysql.TimestampColumn("updated_at")
		allColumns       = mysql.ColumnList{IDColumn, DocumentIDColumn, JobColumn, SourceKeyColumn, MetricKeyColumn, Dimension1Column, Dimension2Column, Dimension3Column, ValueColumn, OccurredAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns   = mysql.ColumnList{DocumentIDColumn, JobColumn, SourceKeyColumn, MetricKeyColumn, Dimension1Column, Dimension2Column, Dimension3Column, ValueColumn, OccurredAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns   = mysql.ColumnList{}
	)

	return fivenetDocumentsStatsMetricTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		DocumentID: DocumentIDColumn,
		Job:        JobColumn,
		SourceKey:  SourceKeyColumn,
		MetricKey:  MetricKeyColumn,
		Dimension1: Dimension1Column,
		Dimension2: Dimension2Column,
		Dimension3: Dimension3Column,
		Value:      ValueColumn,
		OccurredAt: OccurredAtColumn,
		CreatedAt:  CreatedAtColumn,
		UpdatedAt:  UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
