//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetMailerEmailsVisibilityCreator = newFivenetMailerEmailsVisibilityCreatorTable("", "fivenet_mailer_emails_visibility_creator", "")

type fivenetMailerEmailsVisibilityCreatorTable struct {
	mysql.Table

	// Columns
	TargetID   mysql.ColumnInteger
	CreatorID  mysql.ColumnInteger
	CreatorJob mysql.ColumnString
	CreatedAt  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetMailerEmailsVisibilityCreatorTable struct {
	fivenetMailerEmailsVisibilityCreatorTable

	NEW fivenetMailerEmailsVisibilityCreatorTable
}

// AS creates new FivenetMailerEmailsVisibilityCreatorTable with assigned alias
func (a FivenetMailerEmailsVisibilityCreatorTable) AS(alias string) *FivenetMailerEmailsVisibilityCreatorTable {
	return newFivenetMailerEmailsVisibilityCreatorTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetMailerEmailsVisibilityCreatorTable with assigned schema name
func (a FivenetMailerEmailsVisibilityCreatorTable) FromSchema(schemaName string) *FivenetMailerEmailsVisibilityCreatorTable {
	return newFivenetMailerEmailsVisibilityCreatorTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetMailerEmailsVisibilityCreatorTable with assigned table prefix
func (a FivenetMailerEmailsVisibilityCreatorTable) WithPrefix(prefix string) *FivenetMailerEmailsVisibilityCreatorTable {
	return newFivenetMailerEmailsVisibilityCreatorTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetMailerEmailsVisibilityCreatorTable with assigned table suffix
func (a FivenetMailerEmailsVisibilityCreatorTable) WithSuffix(suffix string) *FivenetMailerEmailsVisibilityCreatorTable {
	return newFivenetMailerEmailsVisibilityCreatorTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetMailerEmailsVisibilityCreatorTable(schemaName, tableName, alias string) *FivenetMailerEmailsVisibilityCreatorTable {
	return &FivenetMailerEmailsVisibilityCreatorTable{
		fivenetMailerEmailsVisibilityCreatorTable: newFivenetMailerEmailsVisibilityCreatorTableImpl(schemaName, tableName, alias),
		NEW: newFivenetMailerEmailsVisibilityCreatorTableImpl("", "new", ""),
	}
}

func newFivenetMailerEmailsVisibilityCreatorTableImpl(schemaName, tableName, alias string) fivenetMailerEmailsVisibilityCreatorTable {
	var (
		TargetIDColumn   = mysql.IntegerColumn("target_id")
		CreatorIDColumn  = mysql.IntegerColumn("creator_id")
		CreatorJobColumn = mysql.StringColumn("creator_job")
		CreatedAtColumn  = mysql.TimestampColumn("created_at")
		allColumns       = mysql.ColumnList{TargetIDColumn, CreatorIDColumn, CreatorJobColumn, CreatedAtColumn}
		mutableColumns   = mysql.ColumnList{CreatorIDColumn, CreatorJobColumn, CreatedAtColumn}
		defaultColumns   = mysql.ColumnList{CreatedAtColumn}
	)

	return fivenetMailerEmailsVisibilityCreatorTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TargetID:   TargetIDColumn,
		CreatorID:  CreatorIDColumn,
		CreatorJob: CreatorJobColumn,
		CreatedAt:  CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
