//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetMailerThreadsUserState = newFivenetMailerThreadsUserStateTable("", "fivenet_mailer_threads_user_state", "")

type fivenetMailerThreadsUserStateTable struct {
	mysql.Table

	// Columns
	ThreadID  mysql.ColumnInteger
	UserID    mysql.ColumnInteger
	LastRead  mysql.ColumnTimestamp
	Unread    mysql.ColumnBool
	Important mysql.ColumnBool
	Favorite  mysql.ColumnBool
	Muted     mysql.ColumnBool
	Archived  mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FivenetMailerThreadsUserStateTable struct {
	fivenetMailerThreadsUserStateTable

	NEW fivenetMailerThreadsUserStateTable
}

// AS creates new FivenetMailerThreadsUserStateTable with assigned alias
func (a FivenetMailerThreadsUserStateTable) AS(alias string) *FivenetMailerThreadsUserStateTable {
	return newFivenetMailerThreadsUserStateTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetMailerThreadsUserStateTable with assigned schema name
func (a FivenetMailerThreadsUserStateTable) FromSchema(schemaName string) *FivenetMailerThreadsUserStateTable {
	return newFivenetMailerThreadsUserStateTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetMailerThreadsUserStateTable with assigned table prefix
func (a FivenetMailerThreadsUserStateTable) WithPrefix(prefix string) *FivenetMailerThreadsUserStateTable {
	return newFivenetMailerThreadsUserStateTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetMailerThreadsUserStateTable with assigned table suffix
func (a FivenetMailerThreadsUserStateTable) WithSuffix(suffix string) *FivenetMailerThreadsUserStateTable {
	return newFivenetMailerThreadsUserStateTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetMailerThreadsUserStateTable(schemaName, tableName, alias string) *FivenetMailerThreadsUserStateTable {
	return &FivenetMailerThreadsUserStateTable{
		fivenetMailerThreadsUserStateTable: newFivenetMailerThreadsUserStateTableImpl(schemaName, tableName, alias),
		NEW:                                newFivenetMailerThreadsUserStateTableImpl("", "new", ""),
	}
}

func newFivenetMailerThreadsUserStateTableImpl(schemaName, tableName, alias string) fivenetMailerThreadsUserStateTable {
	var (
		ThreadIDColumn  = mysql.IntegerColumn("thread_id")
		UserIDColumn    = mysql.IntegerColumn("user_id")
		LastReadColumn  = mysql.TimestampColumn("last_read")
		UnreadColumn    = mysql.BoolColumn("unread")
		ImportantColumn = mysql.BoolColumn("important")
		FavoriteColumn  = mysql.BoolColumn("favorite")
		MutedColumn     = mysql.BoolColumn("muted")
		ArchivedColumn  = mysql.BoolColumn("archived")
		allColumns      = mysql.ColumnList{ThreadIDColumn, UserIDColumn, LastReadColumn, UnreadColumn, ImportantColumn, FavoriteColumn, MutedColumn, ArchivedColumn}
		mutableColumns  = mysql.ColumnList{LastReadColumn, UnreadColumn, ImportantColumn, FavoriteColumn, MutedColumn, ArchivedColumn}
	)

	return fivenetMailerThreadsUserStateTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ThreadID:  ThreadIDColumn,
		UserID:    UserIDColumn,
		LastRead:  LastReadColumn,
		Unread:    UnreadColumn,
		Important: ImportantColumn,
		Favorite:  FavoriteColumn,
		Muted:     MutedColumn,
		Archived:  ArchivedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
