//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetJobGroupRules = newFivenetJobGroupRulesTable("", "fivenet_job_group_rules", "")

type fivenetJobGroupRulesTable struct {
	mysql.Table

	// Columns
	ID              mysql.ColumnInteger
	GroupID         mysql.ColumnInteger
	RuleType        mysql.ColumnInteger
	Enabled         mysql.ColumnBool
	CreatedByUserID mysql.ColumnInteger
	UpdatedByUserID mysql.ColumnInteger
	CreatedAt       mysql.ColumnTimestamp
	UpdatedAt       mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetJobGroupRulesTable struct {
	fivenetJobGroupRulesTable

	NEW fivenetJobGroupRulesTable
}

// AS creates new FivenetJobGroupRulesTable with assigned alias
func (a FivenetJobGroupRulesTable) AS(alias string) *FivenetJobGroupRulesTable {
	return newFivenetJobGroupRulesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetJobGroupRulesTable with assigned schema name
func (a FivenetJobGroupRulesTable) FromSchema(schemaName string) *FivenetJobGroupRulesTable {
	return newFivenetJobGroupRulesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetJobGroupRulesTable with assigned table prefix
func (a FivenetJobGroupRulesTable) WithPrefix(prefix string) *FivenetJobGroupRulesTable {
	return newFivenetJobGroupRulesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetJobGroupRulesTable with assigned table suffix
func (a FivenetJobGroupRulesTable) WithSuffix(suffix string) *FivenetJobGroupRulesTable {
	return newFivenetJobGroupRulesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetJobGroupRulesTable(schemaName, tableName, alias string) *FivenetJobGroupRulesTable {
	return &FivenetJobGroupRulesTable{
		fivenetJobGroupRulesTable: newFivenetJobGroupRulesTableImpl(schemaName, tableName, alias),
		NEW:                       newFivenetJobGroupRulesTableImpl("", "new", ""),
	}
}

func newFivenetJobGroupRulesTableImpl(schemaName, tableName, alias string) fivenetJobGroupRulesTable {
	var (
		IDColumn              = mysql.IntegerColumn("id")
		GroupIDColumn         = mysql.IntegerColumn("group_id")
		RuleTypeColumn        = mysql.IntegerColumn("rule_type")
		EnabledColumn         = mysql.BoolColumn("enabled")
		CreatedByUserIDColumn = mysql.IntegerColumn("created_by_user_id")
		UpdatedByUserIDColumn = mysql.IntegerColumn("updated_by_user_id")
		CreatedAtColumn       = mysql.TimestampColumn("created_at")
		UpdatedAtColumn       = mysql.TimestampColumn("updated_at")
		allColumns            = mysql.ColumnList{IDColumn, GroupIDColumn, RuleTypeColumn, EnabledColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = mysql.ColumnList{GroupIDColumn, RuleTypeColumn, EnabledColumn, CreatedByUserIDColumn, UpdatedByUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = mysql.ColumnList{EnabledColumn, CreatedAtColumn}
	)

	return fivenetJobGroupRulesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		GroupID:         GroupIDColumn,
		RuleType:        RuleTypeColumn,
		Enabled:         EnabledColumn,
		CreatedByUserID: CreatedByUserIDColumn,
		UpdatedByUserID: UpdatedByUserIDColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
