//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import "github.com/go-jet/jet/v2/mysql"

var (
	FivenetJobGroupLeaders                = newFivenetJobGroupLeadersTable("", "fivenet_job_group_leaders", "")
	FivenetJobGroupManualMembers          = newFivenetJobGroupManualMembersTable("", "fivenet_job_group_manual_members", "")
	FivenetJobGroupMemberExclusions       = newFivenetJobGroupMemberExclusionsTable("", "fivenet_job_group_member_exclusions", "")
	FivenetJobGroupRules                  = newFivenetJobGroupRulesTable("", "fivenet_job_group_rules", "")
	FivenetJobGroupRuleGrades             = newFivenetJobGroupRuleGradesTable("", "fivenet_job_group_rule_grades", "")
	FivenetJobGroupRuleQualifications     = newFivenetJobGroupRuleQualificationsTable("", "fivenet_job_group_rule_qualifications", "")
	FivenetJobGroupRuleQualificationItems = newFivenetJobGroupRuleQualificationItemsTable("", "fivenet_job_group_rule_qualification_items", "")
)

type FivenetJobGroupLeadersTable struct {
	mysql.Table

	GroupID         mysql.ColumnInteger
	UserID          mysql.ColumnInteger
	CreatedByUserID mysql.ColumnInteger
	CreatedAt       mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

func (a FivenetJobGroupLeadersTable) AS(alias string) *FivenetJobGroupLeadersTable {
	return newFivenetJobGroupLeadersTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetJobGroupLeadersTable) FromSchema(schemaName string) *FivenetJobGroupLeadersTable {
	return newFivenetJobGroupLeadersTable(schemaName, a.TableName(), a.Alias())
}

func newFivenetJobGroupLeadersTable(schemaName, tableName, alias string) *FivenetJobGroupLeadersTable {
	groupID := mysql.IntegerColumn("group_id")
	userID := mysql.IntegerColumn("user_id")
	createdByUserID := mysql.IntegerColumn("created_by_user_id")
	createdAt := mysql.TimestampColumn("created_at")
	allColumns := mysql.ColumnList{groupID, userID, createdByUserID, createdAt}

	return &FivenetJobGroupLeadersTable{
		Table:           mysql.NewTable(schemaName, tableName, alias, allColumns...),
		GroupID:         groupID,
		UserID:          userID,
		CreatedByUserID: createdByUserID,
		CreatedAt:       createdAt,
		AllColumns:      allColumns,
		MutableColumns:  allColumns,
		DefaultColumns:  mysql.ColumnList{createdAt},
	}
}

type FivenetJobGroupManualMembersTable struct {
	mysql.Table

	GroupID         mysql.ColumnInteger
	UserID          mysql.ColumnInteger
	Reason          mysql.ColumnString
	CreatedByUserID mysql.ColumnInteger
	CreatedAt       mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

func (a FivenetJobGroupManualMembersTable) AS(alias string) *FivenetJobGroupManualMembersTable {
	return newFivenetJobGroupManualMembersTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetJobGroupManualMembersTable) FromSchema(schemaName string) *FivenetJobGroupManualMembersTable {
	return newFivenetJobGroupManualMembersTable(schemaName, a.TableName(), a.Alias())
}

func newFivenetJobGroupManualMembersTable(schemaName, tableName, alias string) *FivenetJobGroupManualMembersTable {
	groupID := mysql.IntegerColumn("group_id")
	userID := mysql.IntegerColumn("user_id")
	reason := mysql.StringColumn("reason")
	createdByUserID := mysql.IntegerColumn("created_by_user_id")
	createdAt := mysql.TimestampColumn("created_at")
	allColumns := mysql.ColumnList{groupID, userID, reason, createdByUserID, createdAt}

	return &FivenetJobGroupManualMembersTable{
		Table:           mysql.NewTable(schemaName, tableName, alias, allColumns...),
		GroupID:         groupID,
		UserID:          userID,
		Reason:          reason,
		CreatedByUserID: createdByUserID,
		CreatedAt:       createdAt,
		AllColumns:      allColumns,
		MutableColumns:  allColumns,
		DefaultColumns:  mysql.ColumnList{createdAt},
	}
}

type FivenetJobGroupMemberExclusionsTable struct {
	mysql.Table

	GroupID         mysql.ColumnInteger
	UserID          mysql.ColumnInteger
	ReasonType      mysql.ColumnInteger
	Reason          mysql.ColumnString
	CreatedByUserID mysql.ColumnInteger
	CreatedAt       mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

func (a FivenetJobGroupMemberExclusionsTable) AS(alias string) *FivenetJobGroupMemberExclusionsTable {
	return newFivenetJobGroupMemberExclusionsTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetJobGroupMemberExclusionsTable) FromSchema(schemaName string) *FivenetJobGroupMemberExclusionsTable {
	return newFivenetJobGroupMemberExclusionsTable(schemaName, a.TableName(), a.Alias())
}

func newFivenetJobGroupMemberExclusionsTable(schemaName, tableName, alias string) *FivenetJobGroupMemberExclusionsTable {
	groupID := mysql.IntegerColumn("group_id")
	userID := mysql.IntegerColumn("user_id")
	reasonType := mysql.IntegerColumn("reason_type")
	reason := mysql.StringColumn("reason")
	createdByUserID := mysql.IntegerColumn("created_by_user_id")
	createdAt := mysql.TimestampColumn("created_at")
	allColumns := mysql.ColumnList{groupID, userID, reasonType, reason, createdByUserID, createdAt}

	return &FivenetJobGroupMemberExclusionsTable{
		Table:           mysql.NewTable(schemaName, tableName, alias, allColumns...),
		GroupID:         groupID,
		UserID:          userID,
		ReasonType:      reasonType,
		Reason:          reason,
		CreatedByUserID: createdByUserID,
		CreatedAt:       createdAt,
		AllColumns:      allColumns,
		MutableColumns:  allColumns,
		DefaultColumns:  mysql.ColumnList{reasonType, createdAt},
	}
}

type FivenetJobGroupRulesTable struct {
	mysql.Table

	ID              mysql.ColumnInteger
	GroupID         mysql.ColumnInteger
	RuleType        mysql.ColumnInteger
	Enabled         mysql.ColumnBool
	CreatedByUserID mysql.ColumnInteger
	UpdatedByUserID mysql.ColumnInteger
	CreatedAt       mysql.ColumnTimestamp
	UpdatedAt       mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

func (a FivenetJobGroupRulesTable) AS(alias string) *FivenetJobGroupRulesTable {
	return newFivenetJobGroupRulesTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetJobGroupRulesTable) FromSchema(schemaName string) *FivenetJobGroupRulesTable {
	return newFivenetJobGroupRulesTable(schemaName, a.TableName(), a.Alias())
}

func newFivenetJobGroupRulesTable(schemaName, tableName, alias string) *FivenetJobGroupRulesTable {
	id := mysql.IntegerColumn("id")
	groupID := mysql.IntegerColumn("group_id")
	ruleType := mysql.IntegerColumn("rule_type")
	enabled := mysql.BoolColumn("enabled")
	createdByUserID := mysql.IntegerColumn("created_by_user_id")
	updatedByUserID := mysql.IntegerColumn("updated_by_user_id")
	createdAt := mysql.TimestampColumn("created_at")
	updatedAt := mysql.TimestampColumn("updated_at")
	allColumns := mysql.ColumnList{id, groupID, ruleType, enabled, createdByUserID, updatedByUserID, createdAt, updatedAt}

	return &FivenetJobGroupRulesTable{
		Table:           mysql.NewTable(schemaName, tableName, alias, allColumns...),
		ID:              id,
		GroupID:         groupID,
		RuleType:        ruleType,
		Enabled:         enabled,
		CreatedByUserID: createdByUserID,
		UpdatedByUserID: updatedByUserID,
		CreatedAt:       createdAt,
		UpdatedAt:       updatedAt,
		AllColumns:      allColumns,
		MutableColumns:  mysql.ColumnList{groupID, ruleType, enabled, createdByUserID, updatedByUserID, createdAt, updatedAt},
		DefaultColumns:  mysql.ColumnList{enabled, createdAt},
	}
}

type FivenetJobGroupRuleGradesTable struct {
	mysql.Table

	RuleID        mysql.ColumnInteger
	GradeRuleType mysql.ColumnInteger
	Grade         mysql.ColumnInteger
	MinGrade      mysql.ColumnInteger
	MaxGrade      mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

func (a FivenetJobGroupRuleGradesTable) AS(alias string) *FivenetJobGroupRuleGradesTable {
	return newFivenetJobGroupRuleGradesTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetJobGroupRuleGradesTable) FromSchema(schemaName string) *FivenetJobGroupRuleGradesTable {
	return newFivenetJobGroupRuleGradesTable(schemaName, a.TableName(), a.Alias())
}

func newFivenetJobGroupRuleGradesTable(schemaName, tableName, alias string) *FivenetJobGroupRuleGradesTable {
	ruleID := mysql.IntegerColumn("rule_id")
	gradeRuleType := mysql.IntegerColumn("grade_rule_type")
	grade := mysql.IntegerColumn("grade")
	minGrade := mysql.IntegerColumn("min_grade")
	maxGrade := mysql.IntegerColumn("max_grade")
	allColumns := mysql.ColumnList{ruleID, gradeRuleType, grade, minGrade, maxGrade}

	return &FivenetJobGroupRuleGradesTable{
		Table:          mysql.NewTable(schemaName, tableName, alias, allColumns...),
		RuleID:         ruleID,
		GradeRuleType:  gradeRuleType,
		Grade:          grade,
		MinGrade:       minGrade,
		MaxGrade:       maxGrade,
		AllColumns:     allColumns,
		MutableColumns: allColumns,
		DefaultColumns: nil,
	}
}

type FivenetJobGroupRuleQualificationsTable struct {
	mysql.Table

	RuleID                mysql.ColumnInteger
	QualificationRuleType mysql.ColumnInteger
	RequireCompleted      mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

func (a FivenetJobGroupRuleQualificationsTable) AS(alias string) *FivenetJobGroupRuleQualificationsTable {
	return newFivenetJobGroupRuleQualificationsTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetJobGroupRuleQualificationsTable) FromSchema(schemaName string) *FivenetJobGroupRuleQualificationsTable {
	return newFivenetJobGroupRuleQualificationsTable(schemaName, a.TableName(), a.Alias())
}

func newFivenetJobGroupRuleQualificationsTable(schemaName, tableName, alias string) *FivenetJobGroupRuleQualificationsTable {
	ruleID := mysql.IntegerColumn("rule_id")
	qualificationRuleType := mysql.IntegerColumn("qualification_rule_type")
	requireCompleted := mysql.BoolColumn("require_completed")
	allColumns := mysql.ColumnList{ruleID, qualificationRuleType, requireCompleted}

	return &FivenetJobGroupRuleQualificationsTable{
		Table:                 mysql.NewTable(schemaName, tableName, alias, allColumns...),
		RuleID:                ruleID,
		QualificationRuleType: qualificationRuleType,
		RequireCompleted:      requireCompleted,
		AllColumns:            allColumns,
		MutableColumns:        allColumns,
		DefaultColumns:        mysql.ColumnList{requireCompleted},
	}
}

type FivenetJobGroupRuleQualificationItemsTable struct {
	mysql.Table

	RuleID          mysql.ColumnInteger
	QualificationID mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

func (a FivenetJobGroupRuleQualificationItemsTable) AS(alias string) *FivenetJobGroupRuleQualificationItemsTable {
	return newFivenetJobGroupRuleQualificationItemsTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetJobGroupRuleQualificationItemsTable) FromSchema(schemaName string) *FivenetJobGroupRuleQualificationItemsTable {
	return newFivenetJobGroupRuleQualificationItemsTable(schemaName, a.TableName(), a.Alias())
}

func newFivenetJobGroupRuleQualificationItemsTable(schemaName, tableName, alias string) *FivenetJobGroupRuleQualificationItemsTable {
	ruleID := mysql.IntegerColumn("rule_id")
	qualificationID := mysql.IntegerColumn("qualification_id")
	allColumns := mysql.ColumnList{ruleID, qualificationID}

	return &FivenetJobGroupRuleQualificationItemsTable{
		Table:           mysql.NewTable(schemaName, tableName, alias, allColumns...),
		RuleID:          ruleID,
		QualificationID: qualificationID,
		AllColumns:      allColumns,
		MutableColumns:  allColumns,
		DefaultColumns:  nil,
	}
}
