// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the file is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetCalendarVisibilityCreator = newFivenetCalendarVisibilityCreatorTable("", "fivenet_calendar_visibility_creator", "")

type fivenetCalendarVisibilityCreatorTable struct {
	mysql.Table

	TargetID   mysql.ColumnInteger
	CreatorID  mysql.ColumnInteger
	CreatorJob mysql.ColumnString
	CreatedAt  mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetCalendarVisibilityCreatorTable struct {
	fivenetCalendarVisibilityCreatorTable
	NEW fivenetCalendarVisibilityCreatorTable
}

func (a FivenetCalendarVisibilityCreatorTable) AS(alias string) *FivenetCalendarVisibilityCreatorTable {
	return newFivenetCalendarVisibilityCreatorTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetCalendarVisibilityCreatorTable) FromSchema(schemaName string) *FivenetCalendarVisibilityCreatorTable {
	return newFivenetCalendarVisibilityCreatorTable(schemaName, a.TableName(), a.Alias())
}

func (a FivenetCalendarVisibilityCreatorTable) WithPrefix(prefix string) *FivenetCalendarVisibilityCreatorTable {
	return newFivenetCalendarVisibilityCreatorTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

func (a FivenetCalendarVisibilityCreatorTable) WithSuffix(suffix string) *FivenetCalendarVisibilityCreatorTable {
	return newFivenetCalendarVisibilityCreatorTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetCalendarVisibilityCreatorTable(schemaName, tableName, alias string) *FivenetCalendarVisibilityCreatorTable {
	return &FivenetCalendarVisibilityCreatorTable{
		fivenetCalendarVisibilityCreatorTable: newFivenetCalendarVisibilityCreatorTableImpl(schemaName, tableName, alias),
		NEW:                                   newFivenetCalendarVisibilityCreatorTableImpl("", "new", ""),
	}
}

func newFivenetCalendarVisibilityCreatorTableImpl(schemaName, tableName, alias string) fivenetCalendarVisibilityCreatorTable {
	var (
		TargetIDColumn   = mysql.IntegerColumn("target_id")
		CreatorIDColumn  = mysql.IntegerColumn("creator_id")
		CreatorJobColumn = mysql.StringColumn("creator_job")
		CreatedAtColumn  = mysql.TimestampColumn("created_at")
		allColumns       = mysql.ColumnList{TargetIDColumn, CreatorIDColumn, CreatorJobColumn, CreatedAtColumn}
		mutableColumns   = mysql.ColumnList{TargetIDColumn, CreatorIDColumn, CreatorJobColumn, CreatedAtColumn}
		defaultColumns   = mysql.ColumnList{CreatorIDColumn, CreatorJobColumn, CreatedAtColumn}
	)

	return fivenetCalendarVisibilityCreatorTable{
		Table:    mysql.NewTable(schemaName, tableName, alias, allColumns...),
		TargetID: TargetIDColumn, CreatorID: CreatorIDColumn, CreatorJob: CreatorJobColumn, CreatedAt: CreatedAtColumn,
		AllColumns: allColumns, MutableColumns: mutableColumns, DefaultColumns: defaultColumns,
	}
}
