//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetDocumentsTemplatesJobAccess = newFivenetDocumentsTemplatesJobAccessTable("", "fivenet_documents_templates_job_access", "")

type fivenetDocumentsTemplatesJobAccessTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	CreatedAt    mysql.ColumnTimestamp
	UpdatedAt    mysql.ColumnTimestamp
	DeletedAt    mysql.ColumnTimestamp
	TemplateID   mysql.ColumnInteger
	Job          mysql.ColumnString
	MinimumGrade mysql.ColumnInteger
	Access       mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FivenetDocumentsTemplatesJobAccessTable struct {
	fivenetDocumentsTemplatesJobAccessTable

	NEW fivenetDocumentsTemplatesJobAccessTable
}

// AS creates new FivenetDocumentsTemplatesJobAccessTable with assigned alias
func (a FivenetDocumentsTemplatesJobAccessTable) AS(alias string) *FivenetDocumentsTemplatesJobAccessTable {
	return newFivenetDocumentsTemplatesJobAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetDocumentsTemplatesJobAccessTable with assigned schema name
func (a FivenetDocumentsTemplatesJobAccessTable) FromSchema(schemaName string) *FivenetDocumentsTemplatesJobAccessTable {
	return newFivenetDocumentsTemplatesJobAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetDocumentsTemplatesJobAccessTable with assigned table prefix
func (a FivenetDocumentsTemplatesJobAccessTable) WithPrefix(prefix string) *FivenetDocumentsTemplatesJobAccessTable {
	return newFivenetDocumentsTemplatesJobAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetDocumentsTemplatesJobAccessTable with assigned table suffix
func (a FivenetDocumentsTemplatesJobAccessTable) WithSuffix(suffix string) *FivenetDocumentsTemplatesJobAccessTable {
	return newFivenetDocumentsTemplatesJobAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetDocumentsTemplatesJobAccessTable(schemaName, tableName, alias string) *FivenetDocumentsTemplatesJobAccessTable {
	return &FivenetDocumentsTemplatesJobAccessTable{
		fivenetDocumentsTemplatesJobAccessTable: newFivenetDocumentsTemplatesJobAccessTableImpl(schemaName, tableName, alias),
		NEW:                                     newFivenetDocumentsTemplatesJobAccessTableImpl("", "new", ""),
	}
}

func newFivenetDocumentsTemplatesJobAccessTableImpl(schemaName, tableName, alias string) fivenetDocumentsTemplatesJobAccessTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		CreatedAtColumn    = mysql.TimestampColumn("created_at")
		UpdatedAtColumn    = mysql.TimestampColumn("updated_at")
		DeletedAtColumn    = mysql.TimestampColumn("deleted_at")
		TemplateIDColumn   = mysql.IntegerColumn("template_id")
		JobColumn          = mysql.StringColumn("job")
		MinimumGradeColumn = mysql.IntegerColumn("minimum_grade")
		AccessColumn       = mysql.IntegerColumn("access")
		allColumns         = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, TemplateIDColumn, JobColumn, MinimumGradeColumn, AccessColumn}
		mutableColumns     = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, TemplateIDColumn, JobColumn, MinimumGradeColumn, AccessColumn}
	)

	return fivenetDocumentsTemplatesJobAccessTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		CreatedAt:    CreatedAtColumn,
		UpdatedAt:    UpdatedAtColumn,
		DeletedAt:    DeletedAtColumn,
		TemplateID:   TemplateIDColumn,
		Job:          JobColumn,
		MinimumGrade: MinimumGradeColumn,
		Access:       AccessColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
