//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetVehiclesActivity = newFivenetVehiclesActivityTable("", "fivenet_vehicles_activity", "")

type fivenetVehiclesActivityTable struct {
	mysql.Table

	// Columns
	ID         mysql.ColumnInteger
	CreatedAt  mysql.ColumnTimestamp
	CreatorID  mysql.ColumnInteger
	Plate      mysql.ColumnString
	Type       mysql.ColumnInteger
	CreatorJob mysql.ColumnString
	Reason     mysql.ColumnString
	Data       mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetVehiclesActivityTable struct {
	fivenetVehiclesActivityTable

	NEW fivenetVehiclesActivityTable
}

// AS creates new FivenetVehiclesActivityTable with assigned alias
func (a FivenetVehiclesActivityTable) AS(alias string) *FivenetVehiclesActivityTable {
	return newFivenetVehiclesActivityTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetVehiclesActivityTable with assigned schema name
func (a FivenetVehiclesActivityTable) FromSchema(schemaName string) *FivenetVehiclesActivityTable {
	return newFivenetVehiclesActivityTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetVehiclesActivityTable with assigned table prefix
func (a FivenetVehiclesActivityTable) WithPrefix(prefix string) *FivenetVehiclesActivityTable {
	return newFivenetVehiclesActivityTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetVehiclesActivityTable with assigned table suffix
func (a FivenetVehiclesActivityTable) WithSuffix(suffix string) *FivenetVehiclesActivityTable {
	return newFivenetVehiclesActivityTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetVehiclesActivityTable(schemaName, tableName, alias string) *FivenetVehiclesActivityTable {
	return &FivenetVehiclesActivityTable{
		fivenetVehiclesActivityTable: newFivenetVehiclesActivityTableImpl(schemaName, tableName, alias),
		NEW:                          newFivenetVehiclesActivityTableImpl("", "new", ""),
	}
}

func newFivenetVehiclesActivityTableImpl(schemaName, tableName, alias string) fivenetVehiclesActivityTable {
	var (
		IDColumn         = mysql.IntegerColumn("id")
		CreatedAtColumn  = mysql.TimestampColumn("created_at")
		CreatorIDColumn  = mysql.IntegerColumn("creator_id")
		PlateColumn      = mysql.StringColumn("plate")
		TypeColumn       = mysql.IntegerColumn("type")
		CreatorJobColumn = mysql.StringColumn("creator_job")
		ReasonColumn     = mysql.StringColumn("reason")
		DataColumn       = mysql.StringColumn("data")
		allColumns       = mysql.ColumnList{IDColumn, CreatedAtColumn, CreatorIDColumn, PlateColumn, TypeColumn, CreatorJobColumn, ReasonColumn, DataColumn}
		mutableColumns   = mysql.ColumnList{CreatedAtColumn, CreatorIDColumn, PlateColumn, TypeColumn, CreatorJobColumn, ReasonColumn, DataColumn}
		defaultColumns   = mysql.ColumnList{CreatedAtColumn}
	)

	return fivenetVehiclesActivityTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:         IDColumn,
		CreatedAt:  CreatedAtColumn,
		CreatorID:  CreatorIDColumn,
		Plate:      PlateColumn,
		Type:       TypeColumn,
		CreatorJob: CreatorJobColumn,
		Reason:     ReasonColumn,
		Data:       DataColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
