// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the file is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetCalendarVisibilitySubject = newFivenetCalendarVisibilitySubjectTable("", "fivenet_calendar_visibility_subject", "")

type fivenetCalendarVisibilitySubjectTable struct {
	mysql.Table

	TargetID  mysql.ColumnInteger
	SubjectID mysql.ColumnInteger
	Access    mysql.ColumnInteger
	Effect    mysql.ColumnBool
	CreatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetCalendarVisibilitySubjectTable struct {
	fivenetCalendarVisibilitySubjectTable
	NEW fivenetCalendarVisibilitySubjectTable
}

func (a FivenetCalendarVisibilitySubjectTable) AS(alias string) *FivenetCalendarVisibilitySubjectTable {
	return newFivenetCalendarVisibilitySubjectTable(a.SchemaName(), a.TableName(), alias)
}

func (a FivenetCalendarVisibilitySubjectTable) FromSchema(schemaName string) *FivenetCalendarVisibilitySubjectTable {
	return newFivenetCalendarVisibilitySubjectTable(schemaName, a.TableName(), a.Alias())
}

func (a FivenetCalendarVisibilitySubjectTable) WithPrefix(prefix string) *FivenetCalendarVisibilitySubjectTable {
	return newFivenetCalendarVisibilitySubjectTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

func (a FivenetCalendarVisibilitySubjectTable) WithSuffix(suffix string) *FivenetCalendarVisibilitySubjectTable {
	return newFivenetCalendarVisibilitySubjectTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetCalendarVisibilitySubjectTable(schemaName, tableName, alias string) *FivenetCalendarVisibilitySubjectTable {
	return &FivenetCalendarVisibilitySubjectTable{
		fivenetCalendarVisibilitySubjectTable: newFivenetCalendarVisibilitySubjectTableImpl(schemaName, tableName, alias),
		NEW:                                   newFivenetCalendarVisibilitySubjectTableImpl("", "new", ""),
	}
}

func newFivenetCalendarVisibilitySubjectTableImpl(schemaName, tableName, alias string) fivenetCalendarVisibilitySubjectTable {
	var (
		TargetIDColumn  = mysql.IntegerColumn("target_id")
		SubjectIDColumn = mysql.IntegerColumn("subject_id")
		AccessColumn    = mysql.IntegerColumn("access")
		EffectColumn    = mysql.BoolColumn("effect")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		allColumns      = mysql.ColumnList{TargetIDColumn, SubjectIDColumn, AccessColumn, EffectColumn, CreatedAtColumn}
		mutableColumns  = mysql.ColumnList{TargetIDColumn, SubjectIDColumn, AccessColumn, EffectColumn, CreatedAtColumn}
		defaultColumns  = mysql.ColumnList{EffectColumn, CreatedAtColumn}
	)

	return fivenetCalendarVisibilitySubjectTable{
		Table:    mysql.NewTable(schemaName, tableName, alias, allColumns...),
		TargetID: TargetIDColumn, SubjectID: SubjectIDColumn, Access: AccessColumn, Effect: EffectColumn, CreatedAt: CreatedAtColumn,
		AllColumns: allColumns, MutableColumns: mutableColumns, DefaultColumns: defaultColumns,
	}
}
