//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetRoles = newFivenetRolesTable("", "fivenet_roles", "")

type fivenetRolesTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnInteger
	CreatedAt mysql.ColumnTimestamp
	Job       mysql.ColumnString
	Grade     mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetRolesTable struct {
	fivenetRolesTable

	NEW fivenetRolesTable
}

// AS creates new FivenetRolesTable with assigned alias
func (a FivenetRolesTable) AS(alias string) *FivenetRolesTable {
	return newFivenetRolesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetRolesTable with assigned schema name
func (a FivenetRolesTable) FromSchema(schemaName string) *FivenetRolesTable {
	return newFivenetRolesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetRolesTable with assigned table prefix
func (a FivenetRolesTable) WithPrefix(prefix string) *FivenetRolesTable {
	return newFivenetRolesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetRolesTable with assigned table suffix
func (a FivenetRolesTable) WithSuffix(suffix string) *FivenetRolesTable {
	return newFivenetRolesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetRolesTable(schemaName, tableName, alias string) *FivenetRolesTable {
	return &FivenetRolesTable{
		fivenetRolesTable: newFivenetRolesTableImpl(schemaName, tableName, alias),
		NEW:               newFivenetRolesTableImpl("", "new", ""),
	}
}

func newFivenetRolesTableImpl(schemaName, tableName, alias string) fivenetRolesTable {
	var (
		IDColumn        = mysql.IntegerColumn("id")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		JobColumn       = mysql.StringColumn("job")
		GradeColumn     = mysql.IntegerColumn("grade")
		allColumns      = mysql.ColumnList{IDColumn, CreatedAtColumn, JobColumn, GradeColumn}
		mutableColumns  = mysql.ColumnList{CreatedAtColumn, JobColumn, GradeColumn}
		defaultColumns  = mysql.ColumnList{CreatedAtColumn}
	)

	return fivenetRolesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,
		Job:       JobColumn,
		Grade:     GradeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
