//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetJobsRequestsComments = newFivenetJobsRequestsCommentsTable("", "fivenet_jobs_requests_comments", "")

type fivenetJobsRequestsCommentsTable struct {
	mysql.Table

	// Columns
	ID        mysql.ColumnInteger
	CreatedAt mysql.ColumnTimestamp
	UpdatedAt mysql.ColumnTimestamp
	DeletedAt mysql.ColumnTimestamp
	RequestID mysql.ColumnInteger
	Comment   mysql.ColumnString
	CreatorID mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FivenetJobsRequestsCommentsTable struct {
	fivenetJobsRequestsCommentsTable

	NEW fivenetJobsRequestsCommentsTable
}

// AS creates new FivenetJobsRequestsCommentsTable with assigned alias
func (a FivenetJobsRequestsCommentsTable) AS(alias string) *FivenetJobsRequestsCommentsTable {
	return newFivenetJobsRequestsCommentsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetJobsRequestsCommentsTable with assigned schema name
func (a FivenetJobsRequestsCommentsTable) FromSchema(schemaName string) *FivenetJobsRequestsCommentsTable {
	return newFivenetJobsRequestsCommentsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetJobsRequestsCommentsTable with assigned table prefix
func (a FivenetJobsRequestsCommentsTable) WithPrefix(prefix string) *FivenetJobsRequestsCommentsTable {
	return newFivenetJobsRequestsCommentsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetJobsRequestsCommentsTable with assigned table suffix
func (a FivenetJobsRequestsCommentsTable) WithSuffix(suffix string) *FivenetJobsRequestsCommentsTable {
	return newFivenetJobsRequestsCommentsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetJobsRequestsCommentsTable(schemaName, tableName, alias string) *FivenetJobsRequestsCommentsTable {
	return &FivenetJobsRequestsCommentsTable{
		fivenetJobsRequestsCommentsTable: newFivenetJobsRequestsCommentsTableImpl(schemaName, tableName, alias),
		NEW:                              newFivenetJobsRequestsCommentsTableImpl("", "new", ""),
	}
}

func newFivenetJobsRequestsCommentsTableImpl(schemaName, tableName, alias string) fivenetJobsRequestsCommentsTable {
	var (
		IDColumn        = mysql.IntegerColumn("id")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		UpdatedAtColumn = mysql.TimestampColumn("updated_at")
		DeletedAtColumn = mysql.TimestampColumn("deleted_at")
		RequestIDColumn = mysql.IntegerColumn("request_id")
		CommentColumn   = mysql.StringColumn("comment")
		CreatorIDColumn = mysql.IntegerColumn("creator_id")
		allColumns      = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, RequestIDColumn, CommentColumn, CreatorIDColumn}
		mutableColumns  = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, RequestIDColumn, CommentColumn, CreatorIDColumn}
	)

	return fivenetJobsRequestsCommentsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		DeletedAt: DeletedAtColumn,
		RequestID: RequestIDColumn,
		Comment:   CommentColumn,
		CreatorID: CreatorIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
