//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetUserLabelsJobJobAccess = newFivenetUserLabelsJobJobAccessTable("", "fivenet_user_labels_job_job_access", "")

type fivenetUserLabelsJobJobAccessTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	CreatedAt    mysql.ColumnTimestamp
	LabelID      mysql.ColumnInteger
	Job          mysql.ColumnString
	MinimumGrade mysql.ColumnInteger
	Access       mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetUserLabelsJobJobAccessTable struct {
	fivenetUserLabelsJobJobAccessTable

	NEW fivenetUserLabelsJobJobAccessTable
}

// AS creates new FivenetUserLabelsJobJobAccessTable with assigned alias
func (a FivenetUserLabelsJobJobAccessTable) AS(alias string) *FivenetUserLabelsJobJobAccessTable {
	return newFivenetUserLabelsJobJobAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetUserLabelsJobJobAccessTable with assigned schema name
func (a FivenetUserLabelsJobJobAccessTable) FromSchema(schemaName string) *FivenetUserLabelsJobJobAccessTable {
	return newFivenetUserLabelsJobJobAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetUserLabelsJobJobAccessTable with assigned table prefix
func (a FivenetUserLabelsJobJobAccessTable) WithPrefix(prefix string) *FivenetUserLabelsJobJobAccessTable {
	return newFivenetUserLabelsJobJobAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetUserLabelsJobJobAccessTable with assigned table suffix
func (a FivenetUserLabelsJobJobAccessTable) WithSuffix(suffix string) *FivenetUserLabelsJobJobAccessTable {
	return newFivenetUserLabelsJobJobAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetUserLabelsJobJobAccessTable(schemaName, tableName, alias string) *FivenetUserLabelsJobJobAccessTable {
	return &FivenetUserLabelsJobJobAccessTable{
		fivenetUserLabelsJobJobAccessTable: newFivenetUserLabelsJobJobAccessTableImpl(schemaName, tableName, alias),
		NEW:                                newFivenetUserLabelsJobJobAccessTableImpl("", "new", ""),
	}
}

func newFivenetUserLabelsJobJobAccessTableImpl(schemaName, tableName, alias string) fivenetUserLabelsJobJobAccessTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		CreatedAtColumn    = mysql.TimestampColumn("created_at")
		LabelIDColumn      = mysql.IntegerColumn("label_id")
		JobColumn          = mysql.StringColumn("job")
		MinimumGradeColumn = mysql.IntegerColumn("minimum_grade")
		AccessColumn       = mysql.IntegerColumn("access")
		allColumns         = mysql.ColumnList{IDColumn, CreatedAtColumn, LabelIDColumn, JobColumn, MinimumGradeColumn, AccessColumn}
		mutableColumns     = mysql.ColumnList{CreatedAtColumn, LabelIDColumn, JobColumn, MinimumGradeColumn, AccessColumn}
		defaultColumns     = mysql.ColumnList{CreatedAtColumn, MinimumGradeColumn}
	)

	return fivenetUserLabelsJobJobAccessTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		CreatedAt:    CreatedAtColumn,
		LabelID:      LabelIDColumn,
		Job:          JobColumn,
		MinimumGrade: MinimumGradeColumn,
		Access:       AccessColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
