//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetWikiPagesAccess = newFivenetWikiPagesAccessTable("", "fivenet_wiki_pages_access", "")

type fivenetWikiPagesAccessTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	TargetID     mysql.ColumnInteger
	UserID       mysql.ColumnInteger
	Job          mysql.ColumnString
	MinimumGrade mysql.ColumnInteger
	Access       mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetWikiPagesAccessTable struct {
	fivenetWikiPagesAccessTable

	NEW fivenetWikiPagesAccessTable
}

// AS creates new FivenetWikiPagesAccessTable with assigned alias
func (a FivenetWikiPagesAccessTable) AS(alias string) *FivenetWikiPagesAccessTable {
	return newFivenetWikiPagesAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetWikiPagesAccessTable with assigned schema name
func (a FivenetWikiPagesAccessTable) FromSchema(schemaName string) *FivenetWikiPagesAccessTable {
	return newFivenetWikiPagesAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetWikiPagesAccessTable with assigned table prefix
func (a FivenetWikiPagesAccessTable) WithPrefix(prefix string) *FivenetWikiPagesAccessTable {
	return newFivenetWikiPagesAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetWikiPagesAccessTable with assigned table suffix
func (a FivenetWikiPagesAccessTable) WithSuffix(suffix string) *FivenetWikiPagesAccessTable {
	return newFivenetWikiPagesAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetWikiPagesAccessTable(schemaName, tableName, alias string) *FivenetWikiPagesAccessTable {
	return &FivenetWikiPagesAccessTable{
		fivenetWikiPagesAccessTable: newFivenetWikiPagesAccessTableImpl(schemaName, tableName, alias),
		NEW:                         newFivenetWikiPagesAccessTableImpl("", "new", ""),
	}
}

func newFivenetWikiPagesAccessTableImpl(schemaName, tableName, alias string) fivenetWikiPagesAccessTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		TargetIDColumn     = mysql.IntegerColumn("target_id")
		UserIDColumn       = mysql.IntegerColumn("user_id")
		JobColumn          = mysql.StringColumn("job")
		MinimumGradeColumn = mysql.IntegerColumn("minimum_grade")
		AccessColumn       = mysql.IntegerColumn("access")
		allColumns         = mysql.ColumnList{IDColumn, TargetIDColumn, UserIDColumn, JobColumn, MinimumGradeColumn, AccessColumn}
		mutableColumns     = mysql.ColumnList{TargetIDColumn, UserIDColumn, JobColumn, MinimumGradeColumn, AccessColumn}
		defaultColumns     = mysql.ColumnList{}
	)

	return fivenetWikiPagesAccessTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		TargetID:     TargetIDColumn,
		UserID:       UserIDColumn,
		Job:          JobColumn,
		MinimumGrade: MinimumGradeColumn,
		Access:       AccessColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
