//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetInternetAds = newFivenetInternetAdsTable("", "fivenet_internet_ads", "")

type fivenetInternetAdsTable struct {
	mysql.Table

	// Columns
	ID          mysql.ColumnInteger
	CreatedAt   mysql.ColumnTimestamp
	UpdatedAt   mysql.ColumnTimestamp
	DeletedAt   mysql.ColumnTimestamp
	Disabled    mysql.ColumnBool
	AdType      mysql.ColumnInteger
	StartsAt    mysql.ColumnTimestamp
	EndsAt      mysql.ColumnTimestamp
	Title       mysql.ColumnString
	Description mysql.ColumnString
	Image       mysql.ColumnString
	ApproverJob mysql.ColumnString
	ApproverID  mysql.ColumnInteger
	CreatorJob  mysql.ColumnString
	CreatorID   mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetInternetAdsTable struct {
	fivenetInternetAdsTable

	NEW fivenetInternetAdsTable
}

// AS creates new FivenetInternetAdsTable with assigned alias
func (a FivenetInternetAdsTable) AS(alias string) *FivenetInternetAdsTable {
	return newFivenetInternetAdsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetInternetAdsTable with assigned schema name
func (a FivenetInternetAdsTable) FromSchema(schemaName string) *FivenetInternetAdsTable {
	return newFivenetInternetAdsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetInternetAdsTable with assigned table prefix
func (a FivenetInternetAdsTable) WithPrefix(prefix string) *FivenetInternetAdsTable {
	return newFivenetInternetAdsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetInternetAdsTable with assigned table suffix
func (a FivenetInternetAdsTable) WithSuffix(suffix string) *FivenetInternetAdsTable {
	return newFivenetInternetAdsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetInternetAdsTable(schemaName, tableName, alias string) *FivenetInternetAdsTable {
	return &FivenetInternetAdsTable{
		fivenetInternetAdsTable: newFivenetInternetAdsTableImpl(schemaName, tableName, alias),
		NEW:                     newFivenetInternetAdsTableImpl("", "new", ""),
	}
}

func newFivenetInternetAdsTableImpl(schemaName, tableName, alias string) fivenetInternetAdsTable {
	var (
		IDColumn          = mysql.IntegerColumn("id")
		CreatedAtColumn   = mysql.TimestampColumn("created_at")
		UpdatedAtColumn   = mysql.TimestampColumn("updated_at")
		DeletedAtColumn   = mysql.TimestampColumn("deleted_at")
		DisabledColumn    = mysql.BoolColumn("disabled")
		AdTypeColumn      = mysql.IntegerColumn("ad_type")
		StartsAtColumn    = mysql.TimestampColumn("starts_at")
		EndsAtColumn      = mysql.TimestampColumn("ends_at")
		TitleColumn       = mysql.StringColumn("title")
		DescriptionColumn = mysql.StringColumn("description")
		ImageColumn       = mysql.StringColumn("image")
		ApproverJobColumn = mysql.StringColumn("approver_job")
		ApproverIDColumn  = mysql.IntegerColumn("approver_id")
		CreatorJobColumn  = mysql.StringColumn("creator_job")
		CreatorIDColumn   = mysql.IntegerColumn("creator_id")
		allColumns        = mysql.ColumnList{IDColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, DisabledColumn, AdTypeColumn, StartsAtColumn, EndsAtColumn, TitleColumn, DescriptionColumn, ImageColumn, ApproverJobColumn, ApproverIDColumn, CreatorJobColumn, CreatorIDColumn}
		mutableColumns    = mysql.ColumnList{CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn, DisabledColumn, AdTypeColumn, StartsAtColumn, EndsAtColumn, TitleColumn, DescriptionColumn, ImageColumn, ApproverJobColumn, ApproverIDColumn, CreatorJobColumn, CreatorIDColumn}
		defaultColumns    = mysql.ColumnList{CreatedAtColumn, DisabledColumn}
	)

	return fivenetInternetAdsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,
		DeletedAt:   DeletedAtColumn,
		Disabled:    DisabledColumn,
		AdType:      AdTypeColumn,
		StartsAt:    StartsAtColumn,
		EndsAt:      EndsAtColumn,
		Title:       TitleColumn,
		Description: DescriptionColumn,
		Image:       ImageColumn,
		ApproverJob: ApproverJobColumn,
		ApproverID:  ApproverIDColumn,
		CreatorJob:  CreatorJobColumn,
		CreatorID:   CreatorIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
