//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetCentrumSettings = newFivenetCentrumSettingsTable("", "fivenet_centrum_settings", "")

type fivenetCentrumSettingsTable struct {
	mysql.Table

	// Columns
	Job              mysql.ColumnString
	DeletedAt        mysql.ColumnTimestamp
	Enabled          mysql.ColumnBool
	Mode             mysql.ColumnInteger
	FallbackMode     mysql.ColumnInteger
	PredefinedStatus mysql.ColumnString
	Timings          mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetCentrumSettingsTable struct {
	fivenetCentrumSettingsTable

	NEW fivenetCentrumSettingsTable
}

// AS creates new FivenetCentrumSettingsTable with assigned alias
func (a FivenetCentrumSettingsTable) AS(alias string) *FivenetCentrumSettingsTable {
	return newFivenetCentrumSettingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetCentrumSettingsTable with assigned schema name
func (a FivenetCentrumSettingsTable) FromSchema(schemaName string) *FivenetCentrumSettingsTable {
	return newFivenetCentrumSettingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetCentrumSettingsTable with assigned table prefix
func (a FivenetCentrumSettingsTable) WithPrefix(prefix string) *FivenetCentrumSettingsTable {
	return newFivenetCentrumSettingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetCentrumSettingsTable with assigned table suffix
func (a FivenetCentrumSettingsTable) WithSuffix(suffix string) *FivenetCentrumSettingsTable {
	return newFivenetCentrumSettingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetCentrumSettingsTable(schemaName, tableName, alias string) *FivenetCentrumSettingsTable {
	return &FivenetCentrumSettingsTable{
		fivenetCentrumSettingsTable: newFivenetCentrumSettingsTableImpl(schemaName, tableName, alias),
		NEW:                         newFivenetCentrumSettingsTableImpl("", "new", ""),
	}
}

func newFivenetCentrumSettingsTableImpl(schemaName, tableName, alias string) fivenetCentrumSettingsTable {
	var (
		JobColumn              = mysql.StringColumn("job")
		DeletedAtColumn        = mysql.TimestampColumn("deleted_at")
		EnabledColumn          = mysql.BoolColumn("enabled")
		ModeColumn             = mysql.IntegerColumn("mode")
		FallbackModeColumn     = mysql.IntegerColumn("fallback_mode")
		PredefinedStatusColumn = mysql.StringColumn("predefined_status")
		TimingsColumn          = mysql.StringColumn("timings")
		allColumns             = mysql.ColumnList{JobColumn, DeletedAtColumn, EnabledColumn, ModeColumn, FallbackModeColumn, PredefinedStatusColumn, TimingsColumn}
		mutableColumns         = mysql.ColumnList{DeletedAtColumn, EnabledColumn, ModeColumn, FallbackModeColumn, PredefinedStatusColumn, TimingsColumn}
		defaultColumns         = mysql.ColumnList{EnabledColumn, ModeColumn, FallbackModeColumn}
	)

	return fivenetCentrumSettingsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Job:              JobColumn,
		DeletedAt:        DeletedAtColumn,
		Enabled:          EnabledColumn,
		Mode:             ModeColumn,
		FallbackMode:     FallbackModeColumn,
		PredefinedStatus: PredefinedStatusColumn,
		Timings:          TimingsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
