//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetInternetDomainsAccess = newFivenetInternetDomainsAccessTable("", "fivenet_internet_domains_access", "")

type fivenetInternetDomainsAccessTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnInteger
	TargetID     mysql.ColumnInteger
	UserID       mysql.ColumnInteger
	Job          mysql.ColumnString
	MinimumGrade mysql.ColumnInteger
	Access       mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type FivenetInternetDomainsAccessTable struct {
	fivenetInternetDomainsAccessTable

	NEW fivenetInternetDomainsAccessTable
}

// AS creates new FivenetInternetDomainsAccessTable with assigned alias
func (a FivenetInternetDomainsAccessTable) AS(alias string) *FivenetInternetDomainsAccessTable {
	return newFivenetInternetDomainsAccessTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetInternetDomainsAccessTable with assigned schema name
func (a FivenetInternetDomainsAccessTable) FromSchema(schemaName string) *FivenetInternetDomainsAccessTable {
	return newFivenetInternetDomainsAccessTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetInternetDomainsAccessTable with assigned table prefix
func (a FivenetInternetDomainsAccessTable) WithPrefix(prefix string) *FivenetInternetDomainsAccessTable {
	return newFivenetInternetDomainsAccessTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetInternetDomainsAccessTable with assigned table suffix
func (a FivenetInternetDomainsAccessTable) WithSuffix(suffix string) *FivenetInternetDomainsAccessTable {
	return newFivenetInternetDomainsAccessTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetInternetDomainsAccessTable(schemaName, tableName, alias string) *FivenetInternetDomainsAccessTable {
	return &FivenetInternetDomainsAccessTable{
		fivenetInternetDomainsAccessTable: newFivenetInternetDomainsAccessTableImpl(schemaName, tableName, alias),
		NEW:                               newFivenetInternetDomainsAccessTableImpl("", "new", ""),
	}
}

func newFivenetInternetDomainsAccessTableImpl(schemaName, tableName, alias string) fivenetInternetDomainsAccessTable {
	var (
		IDColumn           = mysql.IntegerColumn("id")
		TargetIDColumn     = mysql.IntegerColumn("target_id")
		UserIDColumn       = mysql.IntegerColumn("user_id")
		JobColumn          = mysql.StringColumn("job")
		MinimumGradeColumn = mysql.IntegerColumn("minimum_grade")
		AccessColumn       = mysql.IntegerColumn("access")
		allColumns         = mysql.ColumnList{IDColumn, TargetIDColumn, UserIDColumn, JobColumn, MinimumGradeColumn, AccessColumn}
		mutableColumns     = mysql.ColumnList{TargetIDColumn, UserIDColumn, JobColumn, MinimumGradeColumn, AccessColumn}
	)

	return fivenetInternetDomainsAccessTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		TargetID:     TargetIDColumn,
		UserID:       UserIDColumn,
		Job:          JobColumn,
		MinimumGrade: MinimumGradeColumn,
		Access:       AccessColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
