//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var FivenetWikiPagesVisibilityPublic = newFivenetWikiPagesVisibilityPublicTable("", "fivenet_wiki_pages_visibility_public", "")

type fivenetWikiPagesVisibilityPublicTable struct {
	mysql.Table

	// Columns
	TargetID  mysql.ColumnInteger
	CreatedAt mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type FivenetWikiPagesVisibilityPublicTable struct {
	fivenetWikiPagesVisibilityPublicTable

	NEW fivenetWikiPagesVisibilityPublicTable
}

// AS creates new FivenetWikiPagesVisibilityPublicTable with assigned alias
func (a FivenetWikiPagesVisibilityPublicTable) AS(alias string) *FivenetWikiPagesVisibilityPublicTable {
	return newFivenetWikiPagesVisibilityPublicTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FivenetWikiPagesVisibilityPublicTable with assigned schema name
func (a FivenetWikiPagesVisibilityPublicTable) FromSchema(schemaName string) *FivenetWikiPagesVisibilityPublicTable {
	return newFivenetWikiPagesVisibilityPublicTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FivenetWikiPagesVisibilityPublicTable with assigned table prefix
func (a FivenetWikiPagesVisibilityPublicTable) WithPrefix(prefix string) *FivenetWikiPagesVisibilityPublicTable {
	return newFivenetWikiPagesVisibilityPublicTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FivenetWikiPagesVisibilityPublicTable with assigned table suffix
func (a FivenetWikiPagesVisibilityPublicTable) WithSuffix(suffix string) *FivenetWikiPagesVisibilityPublicTable {
	return newFivenetWikiPagesVisibilityPublicTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFivenetWikiPagesVisibilityPublicTable(schemaName, tableName, alias string) *FivenetWikiPagesVisibilityPublicTable {
	return &FivenetWikiPagesVisibilityPublicTable{
		fivenetWikiPagesVisibilityPublicTable: newFivenetWikiPagesVisibilityPublicTableImpl(schemaName, tableName, alias),
		NEW:                                   newFivenetWikiPagesVisibilityPublicTableImpl("", "new", ""),
	}
}

func newFivenetWikiPagesVisibilityPublicTableImpl(schemaName, tableName, alias string) fivenetWikiPagesVisibilityPublicTable {
	var (
		TargetIDColumn  = mysql.IntegerColumn("target_id")
		CreatedAtColumn = mysql.TimestampColumn("created_at")
		allColumns      = mysql.ColumnList{TargetIDColumn, CreatedAtColumn}
		mutableColumns  = mysql.ColumnList{CreatedAtColumn}
		defaultColumns  = mysql.ColumnList{CreatedAtColumn}
	)

	return fivenetWikiPagesVisibilityPublicTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TargetID:  TargetIDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
