// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"github.com/galexrt/arpanet/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&model.UserActivity{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.UserActivity{}) fail: %s", err)
	}
}

func Test_userActivityQuery(t *testing.T) {
	userActivity := newUserActivity(db)
	userActivity = *userActivity.As(userActivity.TableName())
	_do := userActivity.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(userActivity.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <arpanet_documents_mentions> fail:", err)
		return
	}

	_, ok := userActivity.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from userActivity success")
	}

	err = _do.Create(&model.UserActivity{})
	if err != nil {
		t.Error("create item in table <arpanet_documents_mentions> fail:", err)
	}

	err = _do.Save(&model.UserActivity{})
	if err != nil {
		t.Error("create item in table <arpanet_documents_mentions> fail:", err)
	}

	err = _do.CreateInBatches([]*model.UserActivity{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Select(userActivity.ALL).Take()
	if err != nil {
		t.Error("Take() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <arpanet_documents_mentions> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.UserActivity{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Select(userActivity.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Select(userActivity.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <arpanet_documents_mentions> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.ScanByPage(&model.UserActivity{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <arpanet_documents_mentions> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <arpanet_documents_mentions> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <arpanet_documents_mentions> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <arpanet_documents_mentions> fail:", err)
	}
}
