import type { AttributeValues } from '~~/gen/ts/resources/permissions/attributes/attributes';

export type Template = {
    permissions: PermissionTemplate[];
    attributes: AttributeTemplate[];
};

export type PermissionTemplate = {
    namespace: string;
    service: string;
    name: string;
};

export type AttributeTemplate = {
    namespace: string;
    service: string;
    name: string;
    key: string;
    type: string;
    validValues?: AttributeValues;
};

export const policeJobTemplate: Template = {
    permissions: [
        { namespace: 'auth', service: 'AuthService', name: 'ChooseCharacter' },
        { namespace: 'citizens', service: 'CitizensService', name: 'GetUser' },
        { namespace: 'citizens', service: 'CitizensService', name: 'ListCitizens' },
        { namespace: 'citizens', service: 'CitizensService', name: 'ListUserActivity' },
        { namespace: 'citizens', service: 'CitizensService', name: 'SetUserProps' },
        { namespace: 'vehicles', service: 'VehiclesService', name: 'ListVehicles' },
        { namespace: 'documents', service: 'DocumentsService', name: 'AddDocumentReference' },
        { namespace: 'documents', service: 'DocumentsService', name: 'AddDocumentRelation' },
        { namespace: 'documents', service: 'TemplatesService', name: 'CreateTemplate' },
        { namespace: 'documents', service: 'DocumentsService', name: 'DeleteDocument' },
        { namespace: 'documents', service: 'CategoriesService', name: 'DeleteCategory' },
        { namespace: 'documents', service: 'CommentsService', name: 'DeleteComment' },
        { namespace: 'documents', service: 'TemplatesService', name: 'DeleteTemplate' },
        { namespace: 'documents', service: 'CategoriesService', name: 'ListCategories' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ListDocuments' },
        { namespace: 'documents', service: 'TemplatesService', name: 'ListTemplates' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ListUserDocuments' },
        { namespace: 'documents', service: 'DocumentsService', name: 'UpdateDocument' },
        { namespace: 'livemap', service: 'LivemapService', name: 'Stream' },
        { namespace: 'settings', service: 'SettingsService', name: 'CreateRole' },
        { namespace: 'settings', service: 'SettingsService', name: 'DeleteRole' },
        { namespace: 'settings', service: 'SettingsService', name: 'GetJobProps' },
        { namespace: 'settings', service: 'SettingsService', name: 'GetRoles' },
        { namespace: 'settings', service: 'SettingsService', name: 'SetJobProps' },
        { namespace: 'settings', service: 'SettingsService', name: 'UpdateRolePerms' },
        { namespace: 'settings', service: 'SettingsService', name: 'ViewAuditLog' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ToggleDocument' },
        { namespace: 'centrum', service: 'DispatchesService', name: 'CreateDispatch' },
        { namespace: 'centrum', service: 'CentrumService', name: 'Stream' },
        { namespace: 'centrum', service: 'DispatchesService', name: 'UpdateDispatch' },
        { namespace: 'centrum', service: 'UnitsService', name: 'CreateOrUpdateUnit' },
        { namespace: 'centrum', service: 'UnitsService', name: 'DeleteUnit' },
        { namespace: 'centrum', service: 'DispatchesService', name: 'TakeDispatch' },
        { namespace: 'centrum', service: 'CentrumService', name: 'TakeControl' },
        { namespace: 'centrum', service: 'CentrumService', name: 'UpdateSettings' },
        { namespace: 'livemap', service: 'LivemapService', name: 'CreateOrUpdateMarker' },
        { namespace: 'livemap', service: 'LivemapService', name: 'DeleteMarker' },
        { namespace: 'centrum', service: 'DispatchesService', name: 'DeleteDispatch' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ListDocumentActivity' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ChangeDocumentOwner' },
        { namespace: 'documents', service: 'DocumentsService', name: 'CreateDocumentReq' },
        { namespace: 'documents', service: 'DocumentsService', name: 'DeleteDocumentReq' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ListDocumentReqs' },
        { namespace: 'jobs', service: 'ConductService', name: 'CreateConductEntry' },
        { namespace: 'jobs', service: 'ConductService', name: 'DeleteConductEntry' },
        { namespace: 'jobs', service: 'ConductService', name: 'ListConductEntries' },
        { namespace: 'jobs', service: 'ConductService', name: 'UpdateConductEntry' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ListColleagues' },
        { namespace: 'jobs', service: 'TimeclockService', name: 'ListTimeclock' },
        { namespace: 'jobs', service: 'JobsService', name: 'SetMOTD' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'GetColleague' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'SetColleagueProps' },
        { namespace: 'jobs', service: 'TimeclockService', name: 'ListInactiveEmployees' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ListColleagueActivity' },
        { namespace: 'qualifications', service: 'QualificationsService', name: 'DeleteQualification' },
        { namespace: 'qualifications', service: 'QualificationsService', name: 'ListQualifications' },
        { namespace: 'qualifications', service: 'QualificationsService', name: 'UpdateQualification' },
        { namespace: 'completor', service: 'CompletorService', name: 'CompleteCitizenLabels' },
        { namespace: 'calendar', service: 'CalendarService', name: 'CreateCalendar' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ToggleDocumentPin' },
        { namespace: 'wiki', service: 'WikiService', name: 'UpdatePage' },
        { namespace: 'wiki', service: 'WikiService', name: 'DeletePage' },
        { namespace: 'wiki', service: 'WikiService', name: 'ListPageActivity' },
        { namespace: 'wiki', service: 'WikiService', name: 'ListPages' },
        { namespace: 'mailer', service: 'MailerService', name: 'CreateOrUpdateEmail' },
        { namespace: 'mailer', service: 'MailerService', name: 'DeleteEmail' },
        { namespace: 'mailer', service: 'MailerService', name: 'ListEmails' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ManageLabels' },
        { namespace: 'documents', service: 'DocumentsService', name: 'SetDocumentReminder' },
        { namespace: 'documents', service: 'CategoriesService', name: 'CreateOrUpdateCategory' },
        { namespace: 'citizens', service: 'CitizensService', name: 'ManageLabels' },
        { namespace: 'centrum', service: 'CentrumService', name: 'UpdateDispatchers' },
        { namespace: 'vehicles', service: 'VehiclesService', name: 'SetVehicleProps' },
        { namespace: 'documents', service: 'ApprovalService', name: 'DeleteApprovalTasks' },
        { namespace: 'documents', service: 'ApprovalService', name: 'RevokeApproval' },
        { namespace: 'documents', service: 'ApprovalService', name: 'UpsertApprovalPolicy' },
        { namespace: 'documents', service: 'ApprovalService', name: 'UpsertApprovalTasks' },
        { namespace: 'documents', service: 'StampsService', name: 'DeleteStamp' },
        { namespace: 'documents', service: 'StampsService', name: 'ListUsableStamps' },
        { namespace: 'documents', service: 'StampsService', name: 'UpsertStamp' },
        { namespace: 'wiki', service: 'WikiService', name: 'CreatePage' },
    ],
    attributes: [
        {
            namespace: 'citizens',
            service: 'CitizensService',
            name: 'GetUser',
            key: 'Jobs',
            type: 'JobGradeList',
            validValues: {
                validValues: {
                    oneofKind: 'jobGradeList',
                    jobGradeList: { fineGrained: false, jobs: {}, grades: {} },
                },
            },
        },
        {
            namespace: 'citizens',
            service: 'CitizensService',
            name: 'ListCitizens',
            key: 'Fields',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: {
                        strings: [
                            'PhoneNumber',
                            'Licenses',
                            'UserProps.Wanted',
                            'UserProps.Job',
                            'UserProps.TrafficInfractionPoints',
                            'UserProps.OpenFines',
                            'UserProps.Mugshot',
                            'UserProps.Labels',
                            'UserProps.Email',
                        ],
                    },
                },
            },
        },
        {
            namespace: 'citizens',
            service: 'CitizensService',
            name: 'ListUserActivity',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['SourceUser', 'Own'] } } },
        },
        {
            namespace: 'citizens',
            service: 'CitizensService',
            name: 'SetUserProps',
            key: 'Fields',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Wanted', 'Job', 'TrafficInfractionPoints', 'Mugshot', 'Labels'] },
                },
            },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'Stream',
            key: 'Players',
            type: 'JobGradeList',
            validValues: {
                validValues: {
                    oneofKind: 'jobGradeList',
                    jobGradeList: { fineGrained: false, jobs: {}, grades: {} },
                },
            },
        },
        {
            namespace: 'documents',
            service: 'DocumentsService',
            name: 'DeleteDocument',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'documents',
            service: 'CommentsService',
            name: 'DeleteComment',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'documents',
            service: 'CategoriesService',
            name: 'ListCategories',
            key: 'Jobs',
            type: 'JobList',
            validValues: { validValues: { oneofKind: 'jobList', jobList: { strings: [] } } },
        },
        {
            namespace: 'documents',
            service: 'DocumentsService',
            name: 'UpdateDocument',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'documents',
            service: 'DocumentsService',
            name: 'ToggleDocument',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'CreateOrUpdateMarker',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'DeleteMarker',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'Stream',
            key: 'Markers',
            type: 'JobList',
            validValues: { validValues: { oneofKind: 'jobList', jobList: { strings: [] } } },
        },
        {
            namespace: 'documents',
            service: 'DocumentsService',
            name: 'ChangeDocumentOwner',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'documents',
            service: 'DocumentsService',
            name: 'CreateDocumentReq',
            key: 'Types',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Access', 'Closure', 'Update', 'Deletion', 'OwnerChange'] },
                },
            },
        },
        {
            namespace: 'jobs',
            service: 'ConductService',
            name: 'ListConductEntries',
            key: 'Access',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Own', 'All'] } } },
        },
        {
            namespace: 'jobs',
            service: 'TimeclockService',
            name: 'ListTimeclock',
            key: 'Access',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['All'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'SetColleagueProps',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'GetColleague',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'ListColleagueActivity',
            key: 'Types',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: {
                        strings: ['HIRED', 'FIRED', 'PROMOTED', 'DEMOTED', 'ABSENCE_DATE', 'NOTE', 'LABELS', 'NAME'],
                    },
                },
            },
        },
        {
            namespace: 'qualifications',
            service: 'QualificationsService',
            name: 'DeleteQualification',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'qualifications',
            service: 'QualificationsService',
            name: 'UpdateQualification',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'completor',
            service: 'CompletorService',
            name: 'CompleteCitizenLabels',
            key: 'Jobs',
            type: 'JobList',
            validValues: { validValues: { oneofKind: 'jobList', jobList: { strings: [] } } },
        },
        {
            namespace: 'calendar',
            service: 'CalendarService',
            name: 'CreateCalendar',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Job', 'Public'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'GetColleague',
            key: 'Types',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Note', 'Labels'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'SetColleagueProps',
            key: 'Types',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['AbsenceDate', 'Note', 'Labels', 'Name'] },
                },
            },
        },
        {
            namespace: 'wiki',
            service: 'WikiService',
            name: 'UpdatePage',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Public'] } } },
        },
        {
            namespace: 'mailer',
            service: 'MailerService',
            name: 'CreateOrUpdateEmail',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Job'] } } },
        },
        {
            namespace: 'documents',
            service: 'DocumentsService',
            name: 'ToggleDocumentPin',
            key: 'Types',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['JobWide'] } } },
        },
        {
            namespace: 'qualifications',
            service: 'QualificationsService',
            name: 'UpdateQualification',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Public'] } } },
        },
        {
            namespace: 'centrum',
            service: 'CentrumService',
            name: 'UpdateSettings',
            key: 'Access',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Shared', 'Public'] } } },
        },
        {
            namespace: 'vehicles',
            service: 'VehiclesService',
            name: 'ListVehicles',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Wanted'] } } },
        },
        {
            namespace: 'vehicles',
            service: 'VehiclesService',
            name: 'SetVehicleProps',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Wanted'] } } },
        },
    ],
};

export const neutralJobTemplate: Template = {
    permissions: [
        { namespace: 'auth', service: 'AuthService', name: 'ChooseCharacter' },
        { namespace: 'documents', service: 'CategoriesService', name: 'ListCategories' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ListDocuments' },
        { namespace: 'livemap', service: 'LivemapService', name: 'Stream' },
        { namespace: 'settings', service: 'SettingsService', name: 'CreateRole' },
        { namespace: 'settings', service: 'SettingsService', name: 'DeleteRole' },
        { namespace: 'settings', service: 'SettingsService', name: 'GetJobProps' },
        { namespace: 'settings', service: 'SettingsService', name: 'GetRoles' },
        { namespace: 'settings', service: 'SettingsService', name: 'SetJobProps' },
        { namespace: 'settings', service: 'SettingsService', name: 'UpdateRolePerms' },
        { namespace: 'livemap', service: 'LivemapService', name: 'CreateOrUpdateMarker' },
        { namespace: 'livemap', service: 'LivemapService', name: 'DeleteMarker' },
        { namespace: 'jobs', service: 'ConductService', name: 'CreateConductEntry' },
        { namespace: 'jobs', service: 'ConductService', name: 'DeleteConductEntry' },
        { namespace: 'jobs', service: 'ConductService', name: 'ListConductEntries' },
        { namespace: 'jobs', service: 'ConductService', name: 'UpdateConductEntry' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ListColleagues' },
        { namespace: 'jobs', service: 'TimeclockService', name: 'ListTimeclock' },
        { namespace: 'jobs', service: 'JobsService', name: 'SetMOTD' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'GetColleague' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'SetColleagueProps' },
        { namespace: 'jobs', service: 'TimeclockService', name: 'ListInactiveEmployees' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ListColleagueActivity' },
        { namespace: 'calendar', service: 'CalendarService', name: 'CreateCalendar' },
        { namespace: 'wiki', service: 'WikiService', name: 'UpdatePage' },
        { namespace: 'wiki', service: 'WikiService', name: 'DeletePage' },
        { namespace: 'wiki', service: 'WikiService', name: 'ListPageActivity' },
        { namespace: 'wiki', service: 'WikiService', name: 'ListPages' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ManageLabels' },
        { namespace: 'wiki', service: 'WikiService', name: 'CreatePage' },
    ],
    attributes: [
        {
            namespace: 'documents',
            service: 'CategoriesService',
            name: 'ListCategories',
            key: 'Jobs',
            type: 'JobList',
            validValues: { validValues: { oneofKind: 'jobList', jobList: { strings: [] } } },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'CreateOrUpdateMarker',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'DeleteMarker',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'Stream',
            key: 'Markers',
            type: 'JobList',
            validValues: undefined,
        },
        {
            namespace: 'jobs',
            service: 'ConductService',
            name: 'ListConductEntries',
            key: 'Access',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Own', 'All'] } } },
        },
        {
            namespace: 'jobs',
            service: 'TimeclockService',
            name: 'ListTimeclock',
            key: 'Access',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['All'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'SetColleagueProps',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'GetColleague',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'ListColleagueActivity',
            key: 'Types',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: {
                        strings: ['HIRED', 'FIRED', 'PROMOTED', 'DEMOTED', 'ABSENCE_DATE', 'NOTE', 'LABELS', 'NAME'],
                    },
                },
            },
        },
        {
            namespace: 'qualifications',
            service: 'QualificationsService',
            name: 'UpdateQualification',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'calendar',
            service: 'CalendarService',
            name: 'CreateCalendar',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Job', 'Public'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'GetColleague',
            key: 'Types',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Note', 'Labels'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'SetColleagueProps',
            key: 'Types',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['AbsenceDate', 'Note', 'Labels', 'Name'] },
                },
            },
        },
        {
            namespace: 'wiki',
            service: 'WikiService',
            name: 'UpdatePage',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Public'] } } },
        },
        {
            namespace: 'mailer',
            service: 'MailerService',
            name: 'CreateOrUpdateEmail',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Job'] } } },
        },
    ],
};

export const gangJobTemplate: Template = {
    permissions: [
        { namespace: 'auth', service: 'AuthService', name: 'ChooseCharacter' },
        { namespace: 'documents', service: 'DocumentsService', name: 'ListDocuments' },
        { namespace: 'livemap', service: 'LivemapService', name: 'Stream' },
        { namespace: 'settings', service: 'SettingsService', name: 'CreateRole' },
        { namespace: 'settings', service: 'SettingsService', name: 'DeleteRole' },
        { namespace: 'settings', service: 'SettingsService', name: 'GetJobProps' },
        { namespace: 'settings', service: 'SettingsService', name: 'GetRoles' },
        { namespace: 'settings', service: 'SettingsService', name: 'SetJobProps' },
        { namespace: 'settings', service: 'SettingsService', name: 'UpdateRolePerms' },
        { namespace: 'livemap', service: 'LivemapService', name: 'CreateOrUpdateMarker' },
        { namespace: 'livemap', service: 'LivemapService', name: 'DeleteMarker' },
        { namespace: 'jobs', service: 'ConductService', name: 'CreateConductEntry' },
        { namespace: 'jobs', service: 'ConductService', name: 'DeleteConductEntry' },
        { namespace: 'jobs', service: 'ConductService', name: 'ListConductEntries' },
        { namespace: 'jobs', service: 'ConductService', name: 'UpdateConductEntry' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ListColleagues' },
        { namespace: 'jobs', service: 'TimeclockService', name: 'ListTimeclock' },
        { namespace: 'jobs', service: 'JobsService', name: 'SetMOTD' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'GetColleague' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'SetColleagueProps' },
        { namespace: 'jobs', service: 'TimeclockService', name: 'ListInactiveEmployees' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ListColleagueActivity' },
        { namespace: 'calendar', service: 'CalendarService', name: 'CreateCalendar' },
        { namespace: 'wiki', service: 'WikiService', name: 'DeletePage' },
        { namespace: 'mailer', service: 'MailerService', name: 'CreateOrUpdateEmail' },
        { namespace: 'mailer', service: 'MailerService', name: 'DeleteEmail' },
        { namespace: 'mailer', service: 'MailerService', name: 'ListEmails' },
        { namespace: 'jobs', service: 'ColleaguesService', name: 'ManageLabels' },
    ],
    attributes: [
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'CreateOrUpdateMarker',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'DeleteMarker',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'livemap',
            service: 'LivemapService',
            name: 'Stream',
            key: 'Markers',
            type: 'JobList',
            validValues: undefined,
        },
        {
            namespace: 'jobs',
            service: 'ConductService',
            name: 'ListConductEntries',
            key: 'Access',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Own', 'All'] } } },
        },
        {
            namespace: 'jobs',
            service: 'TimeclockService',
            name: 'ListTimeclock',
            key: 'Access',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['All'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'SetColleagueProps',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'GetColleague',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'ListColleagueActivity',
            key: 'Types',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: {
                        strings: ['HIRED', 'FIRED', 'PROMOTED', 'DEMOTED', 'ABSENCE_DATE', 'NOTE', 'LABELS', 'NAME'],
                    },
                },
            },
        },
        {
            namespace: 'qualifications',
            service: 'QualificationsService',
            name: 'UpdateQualification',
            key: 'Access',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['Own', 'Lower_Rank', 'Same_Rank', 'Any'] },
                },
            },
        },
        {
            namespace: 'calendar',
            service: 'CalendarService',
            name: 'CreateCalendar',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Job'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'GetColleague',
            key: 'Types',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Note', 'Labels'] } } },
        },
        {
            namespace: 'jobs',
            service: 'ColleaguesService',
            name: 'SetColleagueProps',
            key: 'Types',
            type: 'StringList',
            validValues: {
                validValues: {
                    oneofKind: 'stringList',
                    stringList: { strings: ['AbsenceDate', 'Note', 'Labels', 'Name'] },
                },
            },
        },
        {
            namespace: 'wiki',
            service: 'WikiService',
            name: 'UpdatePage',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: [] } } },
        },
        {
            namespace: 'mailer',
            service: 'MailerService',
            name: 'CreateOrUpdateEmail',
            key: 'Fields',
            type: 'StringList',
            validValues: { validValues: { oneofKind: 'stringList', stringList: { strings: ['Job'] } } },
        },
    ],
};
