//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetDocumentsWorkflowState struct {
	DocumentID        int64      `json:"document_id"`
	NextReminderTime  *time.Time `json:"next_reminder_time"`
	NextReminderCount *int32     `json:"next_reminder_count"`
	AutoCloseTime     *time.Time `json:"auto_close_time"`
	ReminderCount     int32      `json:"reminder_count"`
}
