//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetMailerEmailsVisibilitySubject struct {
	TargetID  int64     `sql:"primary_key" json:"target_id"`
	SubjectID int64     `sql:"primary_key" json:"subject_id"`
	Access    int16     `sql:"primary_key" json:"access"`
	Effect    bool      `sql:"primary_key" json:"effect"`
	CreatedAt time.Time `json:"created_at"`
}
