//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type FivenetMailerSettingsBlocked struct {
	SourceAddressID uint64 `sql:"primary_key" json:"source_address_id"`
	TargetAddressID uint64 `sql:"primary_key" json:"target_address_id"`
}
