//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetInternetPages struct {
	ID          int64      `sql:"primary_key" json:"id"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	DomainID    int64      `json:"domain_id"`
	Path        string     `json:"path"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Data        *string    `json:"data"`
	CreatorJob  *string    `json:"creator_job"`
	CreatorID   *int32     `json:"creator_id"`
}
