//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetRbacAttrs struct {
	ID           int64      `sql:"primary_key" json:"id"`
	CreatedAt    *time.Time `json:"created_at"`
	PermissionID int64      `json:"permission_id"`
	Key          string     `json:"key"`
	Type         string     `json:"type"`
	ValidValues  *string    `json:"valid_values"`
}
