//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetOwnedVehicles struct {
	UserID    *int32     `json:"user_id"`
	Job       *string    `json:"job"`
	Plate     string     `sql:"primary_key" json:"plate"`
	Model     *string    `json:"model"`
	Type      string     `json:"type"`
	Data      *string    `json:"data"`
	UpdatedAt *time.Time `json:"updated_at"`
}
