//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type FivenetJobsGrades struct {
	JobName string `sql:"primary_key" json:"job_name"`
	Grade   int32  `sql:"primary_key" json:"grade"`
	Label   string `json:"label"`
}
