//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetDocumentsPins struct {
	DocumentID uint64     `sql:"primary_key" json:"document_id"`
	Job        string     `sql:"primary_key" json:"job"`
	CreatedAt  *time.Time `json:"created_at"`
	State      *bool      `json:"state"`
	CreatorID  int32      `json:"creator_id"`
}
