//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetDocumentsApprovals struct {
	ID           int64      `sql:"primary_key" json:"id"`
	DocumentID   int64      `json:"document_id"`
	SnapshotDate time.Time  `json:"snapshot_date"`
	PolicyID     *int64     `json:"policy_id"`
	TaskID       *int64     `json:"task_id"`
	UserID       int32      `json:"user_id"`
	UserJob      string     `json:"user_job"`
	UserJobGrade *int32     `json:"user_job_grade"`
	Status       int16      `json:"status"`
	Comment      *string    `json:"comment"`
	CreatedAt    time.Time  `json:"created_at"`
	RevokedAt    *time.Time `json:"revoked_at"`
}
