//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetQualificationsActivity struct {
	ID              int64     `sql:"primary_key" json:"id"`
	QualificationID int64     `json:"qualification_id"`
	ActivityType    int8      `json:"activity_type"`
	ActorUserID     *int32    `json:"actor_user_id"`
	TargetUserID    *int32    `json:"target_user_id"`
	Data            *string   `json:"data"`
	AttemptID       *string   `json:"attempt_id"`
	CreatedAt       time.Time `json:"created_at"`
}
