//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetVehiclesActivity struct {
	ID         int64      `sql:"primary_key" json:"id"`
	CreatedAt  *time.Time `json:"created_at"`
	CreatorID  *int32     `json:"creator_id"`
	Plate      string     `json:"plate"`
	Type       int16      `json:"type"`
	CreatorJob *string    `json:"creator_job"`
	Reason     *string    `json:"reason"`
	Data       *string    `json:"data"`
}
