//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type FivenetJobsLabelsUsers struct {
	UserID  int32  `json:"user_id"`
	Job     string `json:"job"`
	LabelID uint64 `json:"label_id"`
}
