//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetJobsUserProps struct {
	UserID      int32      `json:"user_id"`
	AbsenceDate *time.Time `json:"absence_date"`
}
