//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetLawbooks struct {
	ID          int64      `sql:"primary_key" json:"id"`
	CreatedAt   *time.Time `json:"created_at"`
	UpdatedAt   *time.Time `json:"updated_at"`
	Name        string     `json:"name"`
	SortKey     *string    `json:"sort_key"`
	Description *string    `json:"description"`
}
