//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetMailerEmails struct {
	ID        uint64     `sql:"primary_key" json:"id"`
	CreatedAt *time.Time `json:"created_at"`
	UpdatedAt *time.Time `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	Disabled  *bool      `json:"disabled"`
	Job       *string    `json:"job"`
	UserID    *int32     `json:"user_id"`
	Email     *string    `json:"email"`
	Label     string     `json:"label"`
	Internal  *bool      `json:"internal"`
	Signature *string    `json:"signature"`
}
