//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type FivenetDocumentsApprovalTasks struct {
	ID                 int64      `sql:"primary_key" json:"id"`
	DocumentID         int64      `json:"document_id"`
	SnapshotDate       time.Time  `json:"snapshot_date"`
	AssigneeKind       int16      `json:"assignee_kind"`
	UserID             *int32     `json:"user_id"`
	Job                *string    `json:"job"`
	MinimumGrade       *int32     `json:"minimum_grade"`
	DecidedByUserID    *int32     `json:"decided_by_user_id"`
	DecidedByJob       *string    `json:"decided_by_job"`
	DecidedByUserGrade *int32     `json:"decided_by_user_grade"`
	Status             int16      `json:"status"`
	Comment            *string    `json:"comment"`
	CreatedAt          time.Time  `json:"created_at"`
	DecidedAt          *time.Time `json:"decided_at"`
	DueAt              *time.Time `json:"due_at"`
	DecisionCount      int32      `json:"decision_count"`
}
