//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/shopspring/decimal"
	"time"
)

type FivenetCentrumUnitsStatus struct {
	ID         int64            `sql:"primary_key" json:"id"`
	CreatedAt  *time.Time       `json:"created_at"`
	UnitID     int64            `json:"unit_id"`
	Status     int16            `json:"status"`
	Reason     *string          `json:"reason"`
	Code       *string          `json:"code"`
	UserID     *int32           `json:"user_id"`
	X          *decimal.Decimal `json:"x"`
	Y          *decimal.Decimal `json:"y"`
	Postal     *string          `json:"postal"`
	CreatorID  *int32           `json:"creator_id"`
	CreatorJob *string          `json:"creator_job"`
}
