// Code generated by protoc-gen-customizer. DO NOT EDIT.
// source: services/notificator/notificator.proto

package notificator

import "github.com/galexrt/arpanet/pkg/perms"

var PermsRemap = map[string]string{
	// Service: NotificatorService
	"NotificatorService/ReadNotifications": "NotificatorService/GetNotifications",
	"NotificatorService/Stream":            "NotificatorService/GetNotifications",
}

func (s *Server) GetPermsRemap() map[string]string {
	return PermsRemap
}

const (
	NotificatorServicePermKey = "NotificatorService"
)

func init() {
	perms.AddPermsToList([]*perms.Perm{
		// Service: NotificatorService
		{
			Key:  NotificatorServicePermKey,
			Name: "GetNotifications",
		},
	})
}
