basePath: /api/v1
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: arpanet
  version: 0.0.1
paths:
  /auth/:
    get:
      consumes:
      - application/json
      description: Shows your authentication status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show authentication status
      tags:
      - auth
    post:
      consumes:
      - application/json
      description: Authenticate yourself against the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Authenticate yourself
      tags:
      - auth
  /jobs/:
    get:
      consumes:
      - application/json
      description: Return list of currently registered jobs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Return registered Jobs
      tags:
      - jobs
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping
      tags:
      - ping
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
