name: OSV-Scanner PR Scan

on:
  pull_request:
    branches:
      - main
      - develop
  merge_group:
    branches:
      - main
      - develop

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan:
    name: Scan dependencies
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.6.0
