name: 'Push: Test Code & Build Image'
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  workflow_call:
    inputs:
      skipImageBuild:
        description: 'If images should be built'
        default: false
        required: false
        type: boolean

permissions:
  contents: write
  packages: write

jobs:
  golang-tests:
    name: Golang Test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'

      - name: Run Go Tests
        env:
          TZ: "Europe/Berlin"
        run: go test ./...

  node-lint-tests:
    name: Node Lint Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup PNPM
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint
        run: pnpm lint

  node-build-tests:
    name: Node Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup PNPM
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run pnpm build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: pnpm build

  binary-build:
    name: Binaries Build Test
    needs:
      - golang-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build in parallel: linux/amd64, linux/arm64, windows/amd64
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version-file: 'go.mod'

      - name: Run Go Build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o fivenet .

  build-image:
    name: Image Build
    if: ${{ github.event_name != 'pull_request' && !inputs.skipImageBuild }}
    needs:
      - node-lint-tests
      - node-build-tests
      - golang-tests
    uses: ./.github/workflows/build_image.yml
    secrets: inherit

  update-dev-channel:
    name: Update Dev Channel
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    needs:
      - binary-build
      - build-image
    uses: ./.github/workflows/update-channel.yml
    with:
      channel: dev
      image_tag: ${{ needs.build-image.outputs.image_tag }}
