name: Update Release Channel

on:
  workflow_call:
    inputs:
      channel:
        description: 'Which channel to update (stable or dev)'
        required: false
        type: string
        default: 'dev'
      image_tag:
        description: 'The new image tag (appVersion)'
        required: true
        type: string

permissions:
  contents: write

env:
  GH_PAGES_BRANCH: gh-pages
  CHANNEL_NAME: dev

jobs:
  update-channel:
    name: Update ${{ inputs.channel }} Release Channel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make script executable
        run: chmod +x ./internal/scripts/update-release-channel.sh

      - name: Invoke update script
        run: |
          ./internal/scripts/update-release-channel.sh \
            "${{ inputs.channel }}" \
            "${{ inputs.image_tag }}" \
            "${{ inputs.chart_version }}"

      - name: Commit changes on develop
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "ci: bump dev channel to ${{ inputs.image_tag }}"
          file_pattern: |
            channels.json
          branch: develop

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GH_PAGES_BRANCH }}
          path: gh-pages
          fetch-depth: 0

      - name: Publish to gh-pages
        run: |
          cp channels.json gh-pages/channels.json
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add channels.json
          git commit -m "ci: update dev channel image to ${{ inputs.image_tag }}" || echo "No changes to commit"
          git push origin HEAD:${{ env.GH_PAGES_BRANCH }}
